{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}{% trans 'Forum settings' %}{% endblock %}
{% set active_menu = 'system' %}

{% block breadcrumbs %}

    <li class="breadcrumb-item tx-15"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item tx-15"><a  href="{{  'system'|alink }}">{% trans 'Settings' %}</a></li>
    <li class="breadcrumb-item active">{% trans 'Forum settings' %}</li>

{% endblock %}


{% block content %}

<div class="card">
    <div class="card-body mt-0">

    {% set params = admin.extension_config_get({"ext":"mod_forum"}) %}

    <form method="post" action="{{ 'api/admin/extension/config_save'|link }}" class="api-form" data-api-msg="{% trans 'Configuration updated' %}">

            <div class="rowElem noborder">
                <label>{% trans 'Forum points' %}</label>
                <div class="formRight">
                    <div class="row pt-3">
                        <div class="col-md-3">
                            <label class="rdiobox">
                                <input type="radio" name="forum_points_enable" value="1"{% if params.forum_points_enable %} checked="checked"{% endif %}/><span>{% trans 'Enabled' %}</span>
                            </label>
                        </div>
                        <div class="col-md-3">
                            <label class="rdiobox">
                                <input type="radio" name="forum_points_enable" value="0"{% if not params.forum_points_enable %} checked="checked"{% endif %} /><span>{% trans 'Disabled' %}</span>
                            </label>
                        </div>
                    </div>
                 </div>
                <div class="fix"></div>
            </div>

            <div id="forum_points_block" {% if not params.forum_points_enable %}style="display:none;"{% endif %}>
            <div class="rowElem">
                <div class="row">

                        <div class="col-md-2">Give</div>
                        <div class="col-md-3"><input type="text" class="form-control" name="points" value="{{ params.points }}" placeholder="0"></div>
                        <div class="col-md-3">points if post length is longer than</div>
                        <div class="col-md-2" >
                            <input type="text" class="form-control" name="post_length" value="{{params.post_length}}" placeholder="0"/>
                        </div>
                        <div class="col-md-1">symbols</div>

                </div>
                <div class="fix"></div>
            </div>

            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <td style="width: 5%">

                            <input type="checkbox" id="perm-check" />

                        </td>
                        <td>{% trans 'Give points for posting in selected forums' %}</td>
                    </tr>
                </thead>

                <tbody>
                {% for category, forums in admin.forum_get_categories %}
                <tr class="group">
                    <th colspan="2">{{category}}</th>
                </tr>
                {% for forum in forums %}
                <tr>
                    <td>

                        <input type="checkbox" name="points_forums[]" value="{{forum.id}}" class="perm" {% if forum.id in params.points_forums %}checked="checked"{%endif%}/>

                    </td>
                    <td>{{forum.title}}</td>
                </tr>
                {% endfor %}
                {% endfor %}
                </tbody>
            </table>
            <br/>
            </div>

        <button type="submit" value="" class="btn btn-primary  submitForm" ><i class="fe fe-save"></i> {% trans 'Update' %}</button>
            <input type="hidden" name="ext" value="mod_forum" />

    </form>
    </div>
</div>

{% endblock %}

{% block js %}
<script type="text/javascript">

$(function() {
    $('input[name=forum_points_enable]').click(function(){
        if($(this).val() == 1) {
            $('#forum_points_block').slideDown();
        } else {
            $('#forum_points_block').slideUp();
        }
    });

    $('#perm-check').click(function(){
        if($('#perm-check').is(':checked')) {
            $('.perm').prop('checked', true);
        } else {
            $('.perm').prop('checked', false);
        }
        $.uniform.update(".perm");
    });
});

</script>
{% endblock %}
