{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% set active_menu = 'support' %}
{% block meta_title %}Forum{% endblock %}

{% block content %}
<div class="card">
    <div class="card-body">

    <form method="post" action="{{ 'api/admin/forum/update'|link }}" class="save api-form" data-api-redirect="{{ 'forum'|alink }}">

            <div class="rowElem noborder">
                <label>{% trans 'Category' %}:</label>
                <div class="formRight moreFields">
                    <ul>
                        <li style="width: 170px"><input type="text" class='form-control' name="category" value="{{forum.category}}" placeholder="" style="width: 150px"/></li>
                        <li class="sep"></li>
                        <li style="width: 250px"><input type="checkbox" name="update_categories" value="1" placeholder="" checked="checked"/><label>Update same title categories</label></li>
                        <li class="sep"></li>
                    </ul>
                </div>
                <div class="fix"></div>
            </div>
            <div class="rowElem">
                <label>{% trans 'Title' %}:</label>
                <div class="formRight">
                    <input type="text" class='form-control' name="title" value="{{forum.title}}" required="required" placeholder=""/>
                </div>
                <div class="fix"></div>
            </div>
            <div class="rowElem">
                <label>{% trans 'Slug' %}:</label>
                <div class="formRight">
                    <input type="text" class='form-control' name="slug" value="{{forum.slug}}" required="required" placeholder=""/>
                </div>
                <div class="fix"></div>
            </div>
            <div class="rowElem">
                <label>{% trans 'Status' %}:</label>
                <div class="formRight">
                    <div class="row pt-3">
                        <div class="col-md-3">
                            <label class="rdiobox">
                                <input type="radio" name="status" value="active"{% if forum.status == 'active' %} checked="checked"{% endif %}/><span>{% trans 'Active' %}</span>
                            </label>
                        </div>
                        <div class="col-md-3">
                            <label class="rdiobox">
                                <input type="radio" name="status" value="locked"{% if forum.status == 'locked' %} checked="checked"{% endif %}/><span>{% trans 'Locked' %}</span>
                            </label>
                        </div>
                        </div>
                    </div>
                <div class="fix"></div>
            </div>
            <div class="rowElem">
                <label>{% trans 'Description' %}</label>
                <div class="formRight">
                    <textarea name="description" class="form-control" cols="5" rows="4">{{ forum.description }}</textarea>
                </div>
                <div class="fix"></div>
            </div>
            <button type="submit" value="" class="btn btn-primary  submitForm"><i class="fe fe-save"></i> {% trans 'Update' %}</button>
            <input type="hidden" name="id" value="{{ forum.id }}" />

    </form>
</div>
</div>


{% endblock %}
