<div class="rowElem">
    <label>{% trans 'Import existing' %}:</label>
    <div class="formRight">
        <div class="row pt-3">
            <div class="col-md-3">
                <label class="rdiobox">
        <input type="radio" name="config[import]" value="1"/><span>Yes</span>
                </label>
            </div>
            <div class="col-md-3">
                <label class="rdiobox">
        <input type="radio" name="config[import]" value="0" checked="checked" /><span>No</span>
                </label>
            </div>
        </div>
    </div>
    <div class="fix"></div>
</div>

<div class="rowElem">
    <label>{% trans 'Domain' %}:</label>
    <div class="formRight moreFields">
        <ul>
            <li style="width: 200px"><input type="text" class="form-control"  name="config[domain][owndomain_sld]]" value="" placeholder="{% trans 'Domain name' %}"></li>
            <li style="width: 50px"><input type="text" class="form-control"  name="config[domain][owndomain_tld]]" value=".com" placeholder="{% trans 'Domain TLD' %}"></li>
        </ul>
    </div>
    <div class="fix"></div>
</div>

<div class="rowElem">
    <label>{% trans 'Username' %}:</label>
    <div class="formRight">
        <input type="text" class="form-control"  name="config[username]" value="" placeholder="Leave blank to generate"/>
    </div>
    <div class="fix"></div>
</div>

<div class="rowElem">
    <label>{% trans 'Password' %}:</label>
    <div class="formRight">
        <input type="text" class="form-control"  name="config[password]" value="" placeholder="Leave blank to generate"/>
    </div>
    <div class="fix"></div>
</div>

<input type="hidden" name="config[domain][action]" value="owndomain"/>
