{% extends "layout_default.phtml" %}
{% block meta_title %}Email template{% endblock %}
{% set active_menu = 'system' %}

{% block breadcrumbs %}

    <li class="breadcrumb-item tx-15"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item tx-15"><a  href="{{  'system'|alink }}">{% trans 'Settings' %}</a></li>
    <li class="breadcrumb-item tx-15"><a  href="{{  'extension/settings/email'|alink }}">{% trans 'Email' %}</a></li>
    <li class="breadcrumb-item active">{{template.action_code}}</li>

{% endblock %}

{% block content %}

{# if template.vars|length == 0 %}
<div class="alert alert-info">
    <p><strong>{% trans 'INFORMATION' %}: </strong>{% trans 'This email template is deprecated' %}</p>
</div>
{% endif #}

<div class="card">
    <div class="card-body mt-0">
        <div class="panel panel-primary tabs-style-2">
            <div class=" tab-menu-heading">
                <div class="tabs-menu1">

                    <ul class="nav panel-tabs main-nav-line">
                        <li><a class="nav-link active" data-bs-toggle="tab" href="#template">{% trans 'Template' %}</a></li>
                        <li><a class="nav-link" data-bs-toggle="tab"  href="#vars">{% trans 'Variables' %}</a></li>
                        <li><a class="nav-link" data-bs-toggle="tab"  href="#manage" >{% trans 'Template Settings' %}</a></li>
                        <li><a class="nav-link" data-bs-toggle="tab"  href="#reset">{% trans 'Reset template' %}</a></li>
                        <li><a class="nav-link" data-bs-toggle="tab"  href="#examples">{% trans 'Examples' %}</a></li>
                    </ul>
                </div>
            </div>
            <div class="panel-body tabs-menu-body main-content-body-right border">
                <div class="tab-content">
                    <div class="tab-pane active"  id="template" >
                        <div class="help">
                            <h5>{% trans 'Manage email template' %}</h5>
                            <p>{% trans 'Most email templates receives parameters from BoxBilling. You can browse them on "Variables" tab. Copy variable name to email template and hit preview to see parsed content. Please note that values will be different when actual email is sent.' %}</p>
                        </div>
                        <div class="body">
                            <form method="post" action="admin/email/template_update" class="save api-form" data-api-msg="{% trans 'Template updated' %}">

                                <div class="formBottom">
                                    <input type="text" class="form-control" name="subject" value="{{ template.subject }}" id="email-subject" required="required" placeholder="Email subject"/>
                                </div>
                                <div class="formBottom">
                                    <textarea class="form-control" name="content" cols="5" rows="20" id="email-template" required="required" placeholder="Email message">{{ template.content }}</textarea>
                                </div>

                                {% if template.vars %}<button type="button" value="" class="btn btn-info" id="preview-button"><i class="fe fe-monitor"></i> {% trans 'Preview' %}</button>{% else %}{% trans 'Preview mode is disabled until first event occurrence' %}{% endif %}
                                <button type="submit" value="" class="btn btn-primary  submitForm" style="margin: 0;"><i class="fe fe-save"></i> {% trans 'Update' %}</button>
                                <input type="hidden" name="id" value="{{ template.id }}"/>
                                <div class="fix"></div>

                            </form>

                            <div class="pt20" id="preview" style="display: none;">
                                <div class="body esubject mb20" style="background: white; border: 1px dashed grey; overflow: auto;"></div>
                                <div class="body econtent" style="background: white; border: 1px dashed grey; overflow: auto;"></div>
                            </div>
                        </div>
                    </div>

        <div id="manage" class="tab-pane ">
            <div class="help">
                <h5>{% trans 'Template settings' %}</h5>
                <p>{% trans 'Enable or disable this email template.' %}</p>
            </div>
            <form method="post" action="admin/email/template_update" class="save api-form" data-api-msg="{% trans 'Template updated' %}">

                <div class="rowElem noborder">
                    <label>{% trans 'Enabled' %}:</label>
                    <div class="formRight noborder">
                        <div class="row pt-3">
                            <div class="col-md-3">
                                <label class="rdiobox">
                                    <input type="radio" name="enabled" value="1"{% if template.enabled %} checked="checked"{% endif %}/><span>Yes</span>
                                </label>
                            </div>
                            <div class="col-md-3">
                                <label class="rdiobox">
                                    <input type="radio" name="enabled" value="0"{% if not template.enabled %} checked="checked"{% endif %} /><span>No</span>
                                </label>
                            </div>
                        </div>
                      </div>
                    <div class="fix"></div>
                </div>
                <div class="rowElem">
                    <label>{% trans 'Category' %}</label>
                    <div class="formRight">
                        <input type="text" class="form-control" name="category" value="{{ template.category }}" required="required" placeholder="General"/>
                    </div>
                    <div class="fix"></div>
                </div>
                <button type="submit" value="" class="btn btn-primary  submitForm" ><i class="fe fe-save"></i> {% trans 'Update' %}</button>
                <input type="hidden" name="id" value="{{ template.id }}"/>

            </form>
        </div>

        <div id="vars" class="tab-pane ">
            <div class="">
                <h5>{% trans 'List of variables used in this email' %}</h5>
                <p>{% trans 'These values will change when real email is sent. You can pass these variables to admin or guest API to get additional information from database.' %}</p>
            </div>

            <table class="table table-bordered table-striped" id="tableTemplate">
                <thead>
                    <tr>
                        <th>{% trans 'Variable' %}</th>
                        <th>{% trans 'Example value' %}</th>
                    </tr>
                </thead>

                <tbody>
                {% for k,var in template.vars %}
                    {% if var is iterable %}
                        {% for subkey,subvalue in var %}
                            {% if subvalue is iterable %}
                                {% for subsubkey,subsubvalue in var %}
                                    {% if subsubvalue is not iterable %}
                                        <tr>
                                            <td>{{ '{{' }} {{ k }}.{{subkey}}.{{subsubkey}}{{ '}}' }}</td>
                                            <td>{{ subsubvalue }}</td>
                                        </tr>
                                    {% else %}
                                        <tr>
                                            <td>{{ '{{' }} {{ k }}.{{subkey}}.{{subsubkey}}{{ '}}' }}</td>
                                            <td>Array [ ]</td>
                                        </tr>
                                    {% endif %}
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <td>{{ '{{' }} {{ k }}.{{subkey}} {{ '}}' }}</td>
                                    <td>{{ subvalue }}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td>{{ '{{' }} {{ k }} {{ '}}' }}</td>
                            <td>{{ var }}</td>
                        </tr>
                    {% endif %}


                {% endfor %}
                </tbody>
            </table>
        </div>

        <div id="reset" class="tab-pane ">
            <div class="body mainForm">
                <form action="{{ 'api/admin/email/template_reset'|link }}" class="api-form" data-api-reload="1">
                    <div class="row">
                        <div class="col-md-9 pt5">
                            <h5>{% trans 'Reset email template to default' %}</h5>
                        </div>
                        <div class="col-md-3 text-end">
                            <button type="submit" value="" class="btn btn-info"><i class="fe fe-rotate-ccw"></i> {% trans 'Reset to default' %}</button>
                        </div>
                    </div>


                    <input type="hidden" name="code" value="{{ template.action_code }}"/>
                </form>
            </div>
        </div>

        <div id="examples" class="tab-pane ">
            <div class="help">
                <h5>{% trans 'Email templates examples' %}</h5>
                <p>{% trans 'Email template playground. Use this tool to try rendering email templates.' %}</p>
            </div>

            <div class="body">
                <div class="formBottom">
                    <textarea class="form-control" cols="5" rows="20" class="example">{% autoescape false %} {% apply markdown %}

This is an example of markdown syntax in email template

*Italic text*
**Bolded text**

Lists:

* Red
* Green
* Blue

***

Link to login form: <{{ 'login'|link }}>

Company signature: {{ guest.system_company.signature }}

You can event use IF statements in email templates: {% if 1 == 2 %}This will never show{% else %}Of course 1 is not equal 2{% endif %}

***

Accessing Admin API can get information about your BoxBilling, for example how many clients you have:
{% set stats =  admin.stats_get_summary %}
**Total clients:** {{ stats.clients_total }}

{# Comments in email templates. This text is not visible #}
{# Uncomment the line below to see what is the output #}

{#<pre>{% debug stats %}</pre>#}


{% endapply %}{% endautoescape %}</textarea>
                    <button type="button" value="" class="btn btn-info mt10 epb"><i class="fe fe-monitor"></i> {% trans 'Preview' %}</button>
                    <div class="mt20 example-preview" style="padding: 5px; background: white; border: 1px dashed grey; overflow: auto; display: none;"></div>
                </div>
            </div>

        </div>
    </div>
        <div class="fix"></div>
        </div>
    </div>
</div>

{% endblock %}

{% block js %}
<script type="text/javascript">
$(function() {
    $("#tableTemplate").DataTable();
    $('.epb').click(function(){
        var r = $(this).siblings('.example-preview');
        var params = {_tpl:$(this).siblings('textarea').val(), id:'{{template.id}}' };
        bb.post('admin/email/template_render', params, function(result){
            r.html(result).show();
        });

    });

    $('#preview-button').click(function(){
        var params = {_tpl:$('#email-template').val(), id:'{{template.id}}' };
        bb.post('admin/email/template_render', params, function(result){
            $('#preview').show();
            $('#preview .econtent').html(result);
        });

        var params = {_tpl:$('#email-subject').val(), id:'{{template.id}}' };
        bb.post('admin/email/template_render', params, function(result){
            $('#preview').show();
            $('#preview .esubject').html(result);
        });
        return false;
    });
});
</script>
{% endblock %}
