{% extends "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}{{ post.title}}{% endblock %}
{% set active_menu = 'support' %}

{% block breadcrumbs %}

    <li class="breadcrumb-item tx-15"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item tx-15"><a  href="{{  'news'|alink }}">{% trans 'News' %}</a></li>
    <li class="breadcrumb-item active">{{ post.title}}</li>

{% endblock %}

{% block content %}
<div class="card">
    <div class="card-body">
        <h5>{{ post.title}}</h5>
        <form method="post" action="{{ 'api/admin/news/update'|link }}" class="save api-form" data-api-msg="{% trans 'Post updated' %}">
                <p>If the text is very long you can use <strong>&lt;!--more--&gt;</strong> tag. Inserting this tag within the post will create and excerpt of text (before the tag) to be displayed in posts list. Users will be able to see whole content when they click on "Read more" button.</p>
                <br/>
                <textarea name="content" cols="5" rows="20" class="form-control bb-textarea">{{ post.content }}</textarea>
                <button type="submit" value="" class="btn btn-primary  submitForm" ><i class="fe fe-save"></i> {% trans 'Update' %}</button>
                <input type="hidden" name="id" value="{{ post.id }}"/>
        </form>
    </div>
</div>

<div class="card">

    <div class="card-body">
        <h5>{{ post.title}}</h5>


        <form method="post" action="{{ 'api/admin/news/update'|link }}" class="save api-form" data-api-msg="{% trans 'Post updated' %}">

                <div class="rowElem noborder">
                    <label>{% trans 'Title' %}</label>
                    <div class="formRight">
                        <input type="text" class="form-control" name="title" value="{{ post.title }}" required="required"/>
                    </div>
                    <div class="fix"></div>
                </div>

                <div class="rowElem">
                    <label>{% trans 'Slug' %}</label>
                    <div class="formRight">
                        <input type="text" name="slug" class="form-control"  value="{{ post.slug }}" required="required"/>
                    </div>
                    <div class="fix"></div>
                </div>
                <div class="rowElem">
                    <label>{% trans 'Image' %}</label>
                    <div class="formRight">
                        <input type="text" name="image" class="form-control"  value="{{ post.image }}" id="post_image" placeholder="{% trans 'http://www.yourdomain.com/image.jpg' %}"/>
                    </div>
                    <div class="fix"></div>
                </div>
                <div class="rowElem">
                    <label>{% trans 'Status' %}</label>
                    <div class="formRight">
                        <div class="row pt-3">
                            <div class="col-md-3">
                                <label class="rdiobox">
                                    <input type="radio" name="status" value="draft"{% if post.status == 'draft' %} checked="checked"{% endif %}/> <span>Draft</span>
                                </label>
                            </div>
                            <div class="col-md-3">
                                <label class="rdiobox">
                                    <input type="radio" name="status" value="active"{% if post.status == 'active' %} checked="checked"{% endif %} /> <span>Active</span>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="fix"></div>
                </div>
                <div class="rowElem">
                    <label>{% trans 'Date' %}</label>
                    <div class="formRight">
                        <div class="row">
                            <div class="col-md-6">
                                <label class="pt-3">{% trans 'Post created' %}</label>
                                <div class="formRight">
                                    <input type="text" class="form-control"  name="created_at" value="{{post.created_at|date('Y-m-d')}}" required="required" />
                                </div>

                            </div>
                            <div class="col-md-6">
                                <label class="pt-3">{% trans 'Last update' %}</label>
                                <div class="formRight">
                                    <input type="text" class="form-control"  name="updated_at" value="{{post.updated_at|date('Y-m-d')}}" required="required" />
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            <div class="rowElem">
            <button type="submit" value="" class="btn btn-primary  submitForm"><i class="fe fe-save"></i> {% trans 'Update' %}</button>
                <input type="hidden" name="id" value="{{ post.id }}"/>
            </div>
        </form>
        <div class="body">
            <a href="{{ 'news'|alink }}"  title="" class="btn btn-secondary mr10"><i class="fe fe-arrow-left"></i>  {% trans 'Go back' %}</a>
        </div>
    </div>
</div>
{% endblock %}

{% block head %}{{ mf.bb_editor('.bb-textarea') }}{% endblock %}
