{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}{% trans 'Order Button settings' %}{% endblock %}
{% set active_menu = 'system' %}

{% block head%}
<script src='js/jquery.spectrum.js'></script>
<link rel='stylesheet' href='css/spectrum.css' />
{% endblock %}

{% block breadcrumbs %}

    <li class="breadcrumb-item tx-15"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item tx-15"><a  href="{{  'system'|alink }}">{% trans 'Settings' %}</a></li>
    <li class="breadcrumb-item active">{% trans 'Order Button settings' %}</li>

{% endblock %}

{% block content %}

{% set params = admin.extension_config_get({"ext":"mod_orderbutton"}) %}

<div class="card">
    <div class="card-body mt-0">
        <div class="panel panel-primary tabs-style-2">
            <div class=" tab-menu-heading">
                <div class="tabs-menu2">

                    <ul class="nav panel-tabs main-nav-line">
                        <li><a class="nav-link active" data-bs-toggle="tab" href="#tab-index">{% trans 'Order window settings' %}</a></li>
                        <li><a class="nav-link" data-bs-toggle="tab" href="#tab-popup">{% trans 'Advanced settings' %}</a></li>
                    </ul>
                </div>
            </div>
            <div class="panel-body tabs-menu-body main-content-body-right border">
                <form method="post" action="{{ 'api/admin/extension/config_save'|link }}" class="api-form" data-api-reload="Settings updated">
                    <div class="tab-content">
                        <div class="tab-pane active"  id="tab-index">
                         <div class="help">
                             <h5>{% trans 'Order popup settings' %}</h5>
                             <p>{% trans 'Configure how your popup window will look like' %}</p>
                         </div>


                             <div class="rowElem noborder">
                                 <label>{% trans 'Theme color' %}</label>
                                 <div class="formRight moreFields">
                                     <select name="theme_color" class="form-control form-select" id="theme_color">
                                         <option value="green"{% if params.theme_color == 'green' %}selected{% endif %}>{% trans 'Green' %}</option>
                                         <option value="red"{% if params.theme_color == 'red' %}selected{% endif %}>{% trans 'Red' %}</option>
                                         <option value="blue"{% if params.theme_color == 'blue' %}selected{% endif %}>{% trans 'Blue' %}</option>
                                         <option value="dark"{% if params.theme_color == 'dark' %}selected{% endif %}>{% trans 'Dark' %}</option>
                                     </select>
                                 </div>
                                 <div class="fix"></div>
                             </div>

                            <button type="submit" value="" class="btn btn-primary  submitForm" onclick="window.onbeforeunload = null;"><i class="fe fe-save"></i> {% trans 'Update settings' %}</button>
                     </div>

                         <div class="tab-pane" id="tab-popup">
                             <div class="help">
                                 <h5>{% trans 'Advanced settings' %}</h5>
                                 <p>{% trans 'Configure how your popup window will look like' %}</p>
                             </div>


                                <div class="rowElem noborder">
                                     <label>{% trans 'Border radius' %}</label>
                                     <div class="formRight">
                                         <input type="text" class="form-control" name="border_radius" value="{{params.border_radius | default('0') }}" size="3" id="border-radius" style="width: 50px"/>
                                     </div>
                                     <div class="fix"></div>
                                 </div>


                                 <div class="rowElem">
                                     <label>{% trans 'Background' %}</label>
                                     <div class="formRight moreFields">
                                         <ul>
                                             <li class="">{% trans 'Color' %}</li>
                                             <li>
                                                 <input type="hidden" class="colorpick" id="background-color" name="background_color" value="{{params.background_color | default('#000000') }}" />
                                             </li>
                                             <li class="">{% trans 'Opacity' %}</li>
                                             <li>
                                                 <input type="text" class="form-control" id="background-opacity" name="background_opacity" value="{{params.background_opacity | default(50) }}" />
                                             </li>
                                             <li class="">%</li>
                                         </ul>
                                     </div>
                                     <div class="fix"></div>
                                 </div>



                                 <div class="rowElem">
                                     <label>{% trans 'Loader (while content of popup is being loaded)' %}</label>
                                     <div class="formRight moreFields">
                                            {% for i in range(1, 9) %}
                                             {% set loader_link = 'img/assets/loaders/loader'~i~'.gif'%}
                                             <div class="col-md-12">
                                                 <input type="radio" id="loader{{i}}" name="loader" value="{{i}}" {% if params.loader == i%}checked{% endif %} />
                                                 <label for="loader{{i}}">
                                                     <img src="{{ loader_link | mod_asset_url('orderbutton')}}"/>
                                                 </label>
                                             </div>
                                             {% endfor %}

                                     </div>
                                     <div class="fix"></div>
                                 </div>

                                 <div class="rowElem">
                                     <label>{% trans 'Width' %}</label>
                                     <div class="formRight moreFields">
                                         <ul>
                                             <li style="width: 100px"><input type="text" class="form-control" name="popup_width" id="popup_width" value="{{ params.popup_width | default(600) }}" placeholder="600"></li>
                                             <li class="">px</li>
                                         </ul>
                                     </div>
                                     <div class="fix"></div>
                                 </div>


                                 <div class="rowElem" id="position">
                                     <label>{% trans 'Close (ESC key by default)' %}</label>
                                     <div class="formRight moreFields">
                                         <label class="ckbox">
                                         <input type="checkbox" name="background_close" value="1" id="background-close"  {% if params.background_close %}checked{% endif %}/>
                                         <span for="background-close">{% trans 'Click on background closes popup' %}</span>
                                         </label>
                                     </div>
                                     <div class="fix"></div>
                                 </div>

                                 {% if guest.extension_is_on({"mod":"formbuilder"}) %}
                                 <div class="rowElem">
                                     <label>{% trans 'Show values of custom form before checkout' %}</label>
                                     <div class="formRight moreFields">
                                         <label class="ckbox">
                                         <input type="checkbox" name="show_custom_form_values" value="1" id="show-custom-form-values"  {% if params.show_custom_form_values %}checked{% endif %}/>
                                         <span for="show-custom-form-values">{% trans 'User input will be shown before checkout for custom form' %}</span>
                                         </label>
                                     </div>
                                     <div class="fix"></div>
                                 </div>
                                 {% endif %}

                             <button type="submit" value="" class="btn btn-primary  submitForm" onclick="window.onbeforeunload = null;"><i class="fe fe-save"></i> {% trans 'Update settings' %}</button>

                        </div>
                    </div>
                <input type="hidden" name="ext" value="mod_orderbutton" />
                </form>
            </div>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-body mt-0">
        <h5 class="">{% trans 'Order Button code' %}</h5>

        <form class="" style="width:100%">

                <div class="row">
                    <div class="col-md-4">{% trans 'Clicking on html element with classname or ID' %} </div>
                    <div class="col-md-2"><input type="text" class="form-control" name="bind_selector" id="bind_selector" value="{{ params.bind_selector | default('.order-button') }}" placeholder=".order-button"/></div>
                    <div class="col-md-2">{% trans 'will open popup window for' %} </div>
                    <div class="col-md-3">
                        {{ mf.selectbox('product_id', admin.product_get_pairs, request.product_id, 0, 'All products') }}
                    </div>
                    <div class="col-md-1">{% trans 'symbols' %}</div>
                </div>
                <br/>
                <div class="row">
                    <div class="alert alert-info col-md-10 offset-1 ">
                        <h4 class="alert-heading"><i class="fe fe-check-circle me-2 tx-20"></i>{% trans 'IMPORTANT' %}</h4>
                        <p>{% trans 'You need to add ID (if you want to use it for one html element) or class (if you want to use it for multiple elements) in order for it to work' %}</p>
                        <p id="button-info">
                            {% trans 'Add order-button class to your elements which must call popup. For example: ' %}<strong>&lt;button type=&quot;button&quot;<span >&nbsp;class=&quot;order-button</span>&quot; &gt;Order Now&lt;/button&gt;</strong>
                        <p>{% trans 'Add data-product attribute to your element to open specific product. For example:<br/>' %}<strong>&lt;button type=&quot;button&quot; class=&quot;order-button" <span >data-product="2"</span> &gt;Order Product#2 Now &lt;/button&gt;</strong></p>
                        <p>{% trans 'data-product attribute value will be overiden if popup\'s product is selected from select-box above' %}</p>

                    </div>
                </div>

            <div class="rowElem">
                <label class="topLabel"><b>{% trans 'Copy this code to your website' %}</b></label>
                <div class="formBottom">
                    <textarea class="form-control" cols="5" rows="3" id="script-code" onclick="$(this).select()" readonly="readonly"></textarea>
                </div>
                <div class="fix"></div>
            </div>

            <div class="aligncenter" style="margin-bottom: 20px">
                <button type="button" class="btn bg-success-transparent text-success aligncenter" id="load"><span>{% trans 'Try your popup' %}</span></button>
            </div>
    </form>
    </div>
</div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $(function() {
            $("#background-color").spectrum({
                showInput: true,
                showButtons: true,
                showAlpha: false,
                clickoutFiresChange: true,
                theme: "sp-boxbilling",
                showInitial: true,
                preferredFormat: "hex"
            });
            var changed = false;
            window.onbeforeunload = confirmExit;
            function confirmExit()
            {
                if (changed === true){
                    return "There are unsaved changes! If you will exit this page they will be lost. You can save them by clicking on UPDATE SETTINGS button.";
                }
            }

            var generate_link = function(selector){
                selector = (typeof selector === "undefined") ? $('#bind_selector').val() : selector;
                var initial_link = "{{'orderbutton/js' | link({'options' : 1})}}";
                var options = {
                    'width' : $('#popup_width').val(),
                    'theme_color': $('#theme_color').val(),
                    'background_color':$('#background-color').val(),
                    'popup_top':$('#popup-top').val(),
                    'popup_left':$('#popup-left').val(),
                    'background_opacity':$('#background-opacity').val(),
                    'background_close':$('#background-close:checked').val(),
                    'show_custom_form_values':$('#show-custom-form-values:checked').val(),
                    'bind_selector':selector,
                    'border_radius':$('#border-radius').val(),
                    'product_id':$('#product_id').val(),
                    'loader': $('[name=loader]:checked').val()
                }
                var options_url = "";
                $.each(options,function(k,v){
                    if (v !== "" &&  typeof v !== "undefined" ){
                        options_url += "&" + k + "=" + encodeURIComponent(v);
                    }
                });
                var link = initial_link + options_url;
            return link;
            };

            var show_link = function(){
                $('#script-code').text('\<script type="text/javascript" src="' + generate_link() + '"\>\<\/script\>')
             };
            show_link();


            $('#background-close, #show-custom-form-values').click(function(){
                changed = true;
                show_link();
            });
            $('input').bind('input',function(){
                changed = true;
                show_link();
            });
            $('select, #background-color, input:radio').change(function(){
                changed = true;
                show_link();
            });
            $('#bind_selector').bind('input', function(){
                var selector = $(this).val();
                if (selector[0]!="." || selector[0]!="#"){
                    $('#button-info').parent().removeClass('nInformation').addClass('nFailure');
                    $('#button-info').text('{% trans 'It must start with dot(.) if it is classname or with a hashtag(#)' %}');
                }
                if (selector[0]=="."){
                    $('#button-info').parent().removeClass('nFailure').removeClass('nInformation').addClass('nInformation');
                    $('#button-info').html("{% trans 'Add "+selector+" class to your elements which must call popup. For example: ' %}" + '<strong>&lt;button type=&quot;button&quot;'+'<span class="red">'+ ' class=&quot;'+selector.substring(1)+'</span>'+'&quot; &gt;Order Now&lt;/button&gt;</strong>');

                }
                if (selector[0]=="#"){
                    $('#button-info').parent().removeClass('nFailure').removeClass('nInformation').addClass('nInformation');
                    $('#button-info').html("{% trans 'Add "+selector+" ID to your element which must call popup. For example: ' %}" + '<strong>&lt;button type=&quot;button&quot;'+'<span class="red">'+ ' id=&quot;'+selector.substring(1)+'</span>'+'&quot; &gt;Order Now&lt;/button&gt;</strong>');
                }
            });

            $('#load').click(function(){
                var s = $('#bind_selector').val() + new Date().getTime();
                $('body>button').remove()
                $.getScript(generate_link(s), function() {
                    var test_button = $('<button/>').css({"display": "none"}).appendTo('body');
                    if (s.charAt(0) == '.') {
                        test_button.attr('class', s.substring(1));
                    } else {
                        test_button.attr('id', s.substring(1));
                    }

                });
                document.addEventListener('OrderButtonEventsReady', function (e) {
                    $(s).click();
                }, false);
            });
        });

    </script>
{% endblock %}
