{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}{% trans 'Order' %}{% endblock %}

{% set periods = guest.system_periods %}

{% block content_before %}
		<!-- Page Heading/Breadcrumbs -->
         <div class="left-content">
        <span class="main-content-title mg-b-0 mg-b-lg-1">{% trans 'Select Product' %}</span>
        <small class="d-block tx-12 mb-0 text-muted">{% trans 'Choose products we offer for selling' %}</small>
        </div>
		{% include "partial_steps.phtml" with {'selected': 1} %}

        <!-- /.row -->
{% endblock %}
{% block content %}

        <!-- Content Row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="accordion accordion-dark" id="accordion">
				{% for i, category in guest.product_category_get_list.list %}
					<div class="">
                        <div class="card-header">

                           <a class="accordion-toggle" data-bs-toggle="collapse" data-bs-parent="#accordion" href="#collapse-cat{{category.id}}"><i class="fe fe-plus-circle me-2"></i> <strong>{{ category.title }}</strong></a>

                        </div>
                        <div id="collapse-cat{{category.id}}" class="panel-collapse collapse">
							{% set listing_template = 'mod_service'~category.type~'_listing.phtml' %}
							{% if guest.system_template_exists({"file":listing_template}) %}
							<div class="mod_service{{category.type}} panel-body">{% include listing_template %}</div>
							{% else %}
                            <div class="row d-flex align-items-center mt-4">


						<!--	<ul class="list-group"> -->
							{% for product in category.products %}

                                <div class="col-lg-8 col-xl-3 col-md-8 col-sm-12 mt-2">
                                    <div class="card p-3 pricing-card h-100"  style="min-height: 400px">
                                        <div class="card-header text-justified pt-2">
                                            <p class="tx-18 font-weight-semibold mb-1">{{ product.title }}</p>
                                            {% if product.pricing.type == 'recurrent' %}
                                            <p class="tx-14 text-center text-primary mt-3 font-weight-semibold mb-1">
                                                {% trans 'Starting from' %}
                                            </p>
                                            <select name="period" id="period-selector" class="form-control form-select">
                                                {% for code,prices in product.pricing.recurrent %}
                                                {% if prices.enabled %}<option value="{{code}}">{{ prices.price | money_convert }} {{ periods[code] }}</option>{% endif %}
                                                {% endfor %}
                                            </select>
                                            {% else %}
                                            <p class="tx-14 text-center text-primary mt-3 font-weight-semibold mb-1">
                                            {% trans 'Starting from' %}
                                            </p>
                                            <p class="text-center font-weight-semibold mb-1">
                                               <span class="tx-30 me-1">{{ product.price_starting_from | money_convert }}</span><span class="tx-24">
                                             </p>
                                            {% endif %}
                                        </div>
                                        <div class="card-body pt-2 border-0 mt-2">
                                            <p class="tx-13 mb-1">{% if product.icon_url %}
                                            <div class="pull-left">
                                                {{ product.icon_url | img_tag }}
                                            </div>
                                            {% endif %}
                                            {{ product.description|bbmd }}</p>

                                            <!-- <ul class="text-justify pricing-body text-muted ps-0">
                                                 <li class="mb-4"><span class="text-primary me-2 p-1 bg-primary-transparent rounded-pill tx-8"><i class="fa fa-check"></i></span>  <strong> 2 Free</strong> Domain Name</li>
                                                 <li class="mb-4"><span class="text-primary me-2 p-1 bg-primary-transparent  rounded-pill tx-8"><i class="fa fa-check"></i></span> <strong>3 </strong> One-Click Apps</li>
                                                 <li class="mb-4"><span class="text-primary me-2 p-1 bg-primary-transparent  rounded-pill tx-8"><i class="fa fa-check"></i></span> <strong> 1 </strong> Databases</li>
                                                 <li class="mb-4"><span class="text-primary me-2 p-1 bg-primary-transparent  rounded-pill tx-8"><i class="fa fa-check"></i></span> <strong> Money </strong> BackGuarantee</li>
                                                 <li class="mb-6"><span class="text-primary me-2 p-1 bg-primary-transparent  rounded-pill tx-8"><i class="fa fa-check"></i></span> <strong> 24/7</strong> support</li>
                                             </ul>-->
                                        </div>
                                        <div class="card-footer text-center pt-1">
                                         <!--   <p class="text-justify font-weight-semibold mb-1 mt-4">
                                            {% if product.pricing.type == 'recurrent' %}
                                                {% trans 'Starting from' %}
                                                <select name="period" id="period-selector" class="form-control form-select">
                                                    {% for code,prices in product.pricing.recurrent %}
                                                    {% if prices.enabled %}<option value="{{code}}">{{ prices.price | money_convert }} {{ periods[code] }}</option>{% endif %}
                                                    {% endfor %}
                                                </select>
                                                {% else %}
                                                {% trans 'Starting from' %} <strong>{{ product.price_starting_from | money_convert }}</strong>
                                                {% endif %}
                                            </p>-->
                                                <a class="btn btn-lg btn-primary text-white btn-block" href="{{ '/order'|link }}/{{ product.slug }}"><i class="fe fe-shopping-cart"></i> {% trans 'Order  now' %}</a>
                                        </div>
                                    </div>
                                </div>

								<!--<li class="list-group-item">
									<div class="row">
										<div class="col-md-9">
											<h4 class="list-group-item-heading">{{ product.title }}</h4>
											<div class="list-group-item-text">
												{% if product.icon_url %}
												<div class="pull-left">
													{{ product.icon_url | img_tag }}
												</div>
												{% endif %}
												{{ product.description|bbmd }}
											</div>
										</div>
										<div class="col-md-3 text-center">
											<p>
										</div>
									</div>
								</li>-->
							{% endfor %}
							<!--</ul>-->
                            </div>
							{% endif %}


                        </div>
                    </div>
                    <!-- /.panel -->

				{% endfor %}

                </div>
                <!-- /.panel-group -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->

{% endblock %}

{% block sidebar %}
	<div class="well">
		{% include 'partial_currency.phtml' %}
	</div>
{% endblock %}
