{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% import "macro_functions.phtml" as mf %}

{% block meta_title %}{% trans 'Reset password' %}{% endblock %}

{% block content_before %}
<div class="left-content">
    <span class="main-content-title mg-b-0 mg-b-lg-1">{% trans 'Reset password' %}</span>
</div>
<ol class="breadcrumb">
    <li class="breadcrumb-item tx-15"><a href="{{''|link }}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item active" aria-current="page"><b>{% trans 'Reset password' %}</b></li>
</ol>

        <!-- /.row -->
{% endblock %}
{% block content %}
<div class="card">
    <div class="card-body">
			<form method="post" action="" class="api_form" data-api-url="guest/client/reset_password" data-api-msg="{% trans 'Password reset confirmation email was sent' %}">
				<h5>{% trans 'Enter your email to reset password. You will receive new password after reset link is confirmed.' %}</h5>
				<div class="text-center row mt-5">
					<label class="col-md-2">{% trans 'Email Address' %}:&nbsp;&nbsp;</label>
					<input type="email" class="col-md-4 form-control" name="email" value="{{ request.email }}" required="required">

				</div>
                <div class="col-md-12 text-end"><br>
                <input class="btn btn-warning" type="submit" value="{% trans 'Reset password' %}">
                </div>
            </form>
    </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
$(function() {
    $('#password-reset').bind('submit',function(event){
        bb.post(
            'guest/client/reset_password',
            $(this).serialize(),
            function(result) {
                bb.msg('{% trans "Password reset confirmation email was sent" %}');
            }
        );
        return false;
    });
});
</script>
{% endblock %}
