{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% block meta_title %}{{article.title}}{% endblock %}

{% block content_before %}
        <!-- Page Heading/Breadcrumbs -->
<div class="left-content">
    <span class="main-content-title mg-b-0 mg-b-lg-1">{{article.title}}</span>
    <small class="d-block tx-12 mb-0 text-muted">{{article.created_at|date('Y-m-d h:i') }} | {% trans 'Views' %}: {{ article.views }}</small>
    <ol class="breadcrumb">
        <li class="breadcrumb-item tx-15"><a href="{{ 'kb'|link }}">{% trans 'Knowledge base' %}</a></li>
        <li class="breadcrumb-item tx-15"><a href="{{ '/kb'|link }}/{{article.category.slug}}">{{ article.category.title }}</a></li>
        <li class="breadcrumb-item active" aria-current="page"><b>{{ article.title }}</b></li>
    </ol>
</div>

{% endblock %}
{% block content %}
<div class="card">
    <div class="card-body">
	{{article.content|bbmd}}
    </div>
</div>
	<hr>
	<div class="card">
        <div class="card-body">
            <h6>{%trans 'Similar articles' %}</h6>
            <div class="list-group">
                {% for i, kbarticle in guest.kb_article_get_list({"kb_article_category_id":article.kb_article_category_id, "per_page":5}).list %}
                    <a href="{{ '/kb'|link }}/{{article.category.slug}}/{{kbarticle.slug}}" class="list-group-item">{{kbarticle.title}}</a>
                {% endfor %}
            </div>
        </div>
    </div>
	<div class="card">
        <div class="card-body">
        <h4>{% trans 'What are you looking for?' %}</h4>
		<form method="get" action="{{ 'kb'|link }}">
            <div class="input-group">
				<input name="q" type="text" class="form-control" value="{{ request.q }}" placeholder="{% trans 'What are you looking for?' %}">
                <span class="input-group-btn">
                    <button class="btn btn-light" type="submit"><i class="fa fa-search"></i></button>
                </span>
            </div>
		</form>
    </div>

	<div class="text-center">
		<a class="btn btn-light" href="{{ 'kb'|link }}"><i class="fa fa-arrow-left"></i> {% trans 'Back to list' %}</a>
	</div>



{% endblock %}
