{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% block meta_title %}{{category.title}}{% endblock %}

{% block content_before %}
<!-- Page Heading/Breadcrumbs -->
<div class="left-content">
    <span class="main-content-title mg-b-0 mg-b-lg-1">{{category.title}}</span>
    <small class="d-block tx-12 mb-0 text-muted">{{category.description }}</small>
    <ol class="breadcrumb">
        <li class="breadcrumb-item tx-15"><a href="{{ 'kb'|link }}">{% trans 'Knowledge base' %}</a></li>
        <li class="breadcrumb-item active" aria-current="page"><b>{{ category.title }}</b></li>
    </ol>
</div>
{% endblock %}
{% block content %}

		{% if category.articles|length > 0 %}
            <div class="card">
                <div class="card-body">

					{% for i, article in category.articles %}
						<a href="{{ '/kb'|link }}/{{article.category.slug}}/{{article.slug}}" class="list-group-item">{{article.title}}</a>
					{% endfor %}
				</div>
            </div>

            <hr>
            {% else %}
                <p>
                    {% trans 'Try using other keyword. No matches not for keyword:' %}
                    <b>{{ request.q }}</b>
                </p>
            {% endif %}

<div class="card">
    <div class="card-body">
        <h4>{% trans 'What are you looking for?' %}</h4>
		<form method="get" action="{{ 'kb'|link }}">
            <div class="input-group">
				<input name="q" type="text" class="form-control" value="{{ request.q }}" placeholder="{% trans 'What are you looking for?' %}">
                <span class="input-group-btn">
                    <button class="btn btn-light" type="submit"><i class="fa fa-search"></i></button>
                </span>
            </div>
		</form>
    </div>
    </div>

	<div class="text-center">
		<a class="btn btn-light" href="{{ 'kb'|link }}"><i class="fa fa-arrow-left"></i> {% trans 'Back to list' %}</a>
	</div>
{% endblock %}
