{% if list.pages > 1 %}
{% set page = list.page %}

<div class="text-center">
    <ul class="pagination pagination-circled mb-0">
        {% for i in 1..list.pages %}
        {% if i == page %}
        <li class="page-item active"><a href="#" class="page-link" onclick="return false;">{{ i }}</a></li>
        {%else%}
        <li class="page-item"><a  class="page-link" href="?{% for k,v in {}|merge(request)|merge({'page': i}) %}{{k}}={{v}}{% if loop.last == FALSE %}&{%endif%}{% endfor %}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
    </ul>
</div>
{% endif %}
