<div class="rowElem preview">
    <div class="row">
        <div class="col-md-8">

            <label for="{{field.name}}" class="pt-4">{% if field.hide_label != 1 %}{{ field.label }}{% endif %}</label>

            <div class="formRight">
                {% if field.type == "text" %}
                <div class="moreFields allUpper">
                    <ul>
                        <li class="sep">{{field.prefix}}</li>
                        <li style="width: 50%">
                            <input class="form-control" type="text" name="{{ field.name }}" value="{{ field.default_value }}"  id="{{field.name}}"
                                {{ (field.readonly==1)? 'readonly="readonly"' : ''}}
                            />
                        </li>
                        <li class="sep">{{field.suffix}}</li>
                    </ul>
                </div>
                {% elseif field.type == "select" %}
                    {% if field.options is empty %}
                    <ul>
                        <li style="width: 80%"><blockquote>{% trans 'Please click on "Edit" in order to add new select box' %}</blockquote></li>
                    </ul>
                    {% else %}
                        <select name="{{ field.name }}" required="required" class="form-control form-select"  id="{{field.name}}"
                            {{ (field.readonly==1)? 'disabled="disabled"' : ''}}
                            />
                            {% for k,v in field.options %}
                            <option value="{{v}}"
                            {{ (field.default_value == v) ? 'selected' : '' }}>{{k}}</option>
                            {% endfor %}

                        </select>
                    {% endif %}
                {% elseif field.type == "checkbox" %}
                    {% if field.options is empty %}
                    <ul>
                        <li style="width: 80%"><blockquote>{% trans 'Please click on "Edit" in order to add new checkbox' %}</blockquote></li>
                    </ul>
                    {% else %}
                        {% for k,v in field.options %}
                        <label class="ckbox mb-1">
                        <input type="checkbox" name="{{field.name}}" value="{{v}}" id="{{k}}_{{v}}" {% if v in field.default_value %}checked="checked"{% endif %}
                            {{ (field.readonly==1)? 'disabled="disabled"' : ''}}
                    />
                        <span class="mt-1  ml-1" for="{{k}}_{{v}}">{{k}}</span>
                        </label>
                        {% endfor %}
                    {% endif %}
                {% elseif field.type == "radio" %}
                    {% if field.options is empty %}
                        <ul>
                            <li style="width: 80%"><blockquote>{% trans 'Please click on "Edit" in order to add new radio box' %}</blockquote></li>
                        </ul>
                    {% else %}
                        {% for k,v in field.options %}
                        <label class="rdiobox">
                        <input type="radio" name="{{field.name}}" value="{{v}}" id="{{k}}_{{v}}" {{ (field.default_value == v) ? 'checked' : '' }}
                            {{ (field.readonly==1)? 'disabled="disabled"' : ''}}
                    />
                        <span for="{{k}}_{{v}}">{{k}}</span>
                        </label>
                        {% endfor %}
                    {% endif %}
                {% elseif field.type == "textarea" %}
                    <div style="width: auto; max-width:50%;">
                        <textarea name="{{field.name}}" class="form-control" style="width: {{field.options.width}}px; height: {{field.options.height}}px; overflow: scroll;">{{field.default_value}}</textarea>
                    </div>
                {% endif %}
                </div>
            <div class="fix"></div>
        </div>
        <div class="col-md-3 pt-4">

        <!--        <a class="btn14 pr btnIconLeft" href="#" style="display: none;"><img src="images/icons/dark/preview.png" alt="Preview" class="icon">Preview</a>-->
                <a class="btn btn-sm bg-info-transparent text-info ed" href="#"><i class="fe fe-edit"></i></a>
                <a class="btn btn-sm bg-danger-transparent text-danger rm" href="#" data-field-id="{{field.id}}"><i class="fe fe-trash"></i></a>

        </div>
</div>
</div>
