{% extends "layout_default.phtml" %}
{% set active_menu = 'system' %}
{% block meta_title %}{% trans 'Server management' %}{% endblock %}
{% block breadcrumbs %}

    <li class="breadcrumb-item tx-15"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item tx-15"><a  href="{{  'serviceproxmox'|alink }}">{% trans 'Proxmox servers' %}</a></li>
    <li class="breadcrumb-item active">{{ server.name }}</li>

{% endblock %}

{% block content %}
<div class="card">
    <div class="card-body">
        <form method="post" action="{{ 'api/admin/serviceproxmox/server_update'|link }}" id="server-update" class="save api-form" data-api-msg="Server updated">
                <div class="rowElem noborder">
                    <label>{% trans 'Name' %}:</label>
                    <div class="formRight">
                        <input type="text" class="form-control" name="name" value="{{ server.name }}" required="required" placeholder="{% trans 'Unique name to identify this server' %}">
                    </div>
                    <div class="fix"></div>
                </div>
                <div class="rowElem">
                    <label>{% trans 'Group' %}:</label>
                    <div class="formRight">
                        <input type="text" class="form-control" name="group" value="{{ server.group }}" placeholder="{% trans 'Server group' %}">
                    </div>
                    <div class="fix"></div>
                </div>
                <div class="rowElem">
                    <label>{% trans 'IPv4' %}:</label>
                    <div class="formRight">
                        <input type="text" class="form-control" name="ipv4" value="{{ server.ipv4 }}" placeholder="{% trans 'IPv4 address of the server' %}">
                    </div>
                    <div class="fix"></div>
                </div>
                <div class="rowElem">
                    <label>{% trans 'IPv6' %}:</label>
                    <div class="formRight">
                        <input type="text" class="form-control" name="ipv6" value="{{ server.ipv6 }}" placeholder="{% trans 'IPv6 address of the server' %}">
                    </div>
                    <div class="fix"></div>
                </div>
                <div class="rowElem">
                    <label>{% trans 'Hostname' %}:</label>
                    <div class="formRight">
                        <input type="text" class="form-control" name="hostname" value="{{ server.hostname }}" placeholder="{% trans 'server1.yourserverdomain.com' %}">
                    </div>
                    <div class="fix"></div>
                </div>
                <div class="rowElem">
                    <label>{% trans 'Slots' %}:</label>
                    <div class="formRight">
                        <input type="text" class="form-control" name="slots" value="{{ server.slots }}" required="required" placeholder="{% trans 'Maximum number of accounts on this server' %}">
                    </div>
                    <div class="fix"></div>
                </div>
                <div class="rowElem">
                    <label>{% trans 'Root user' %}:</label>
                    <div class="formRight">
                        <input type="text" class="form-control" name="root_user" required="required" value="{{ server.root_user }}" placeholder="{% trans 'Root username' %}">
                    </div>
                    <div class="fix"></div>
                </div>

                <div class="rowElem">
                    <label>{% trans 'Root Password' %}:</label>
                    <div class="formRight">
                        <input type="text" class="form-control" name="root_password" required="required" value="{{ server.root_password }}" placeholder="{% trans 'Root password of the server' %}">
                    </div>
                    <div class="fix"></div>
                </div>

                <div class="rowElem">
                    <label>{% trans 'Extra config' %}:</label>
                    <div class="formRight">
                        <input type="text" class="form-control" name="config" value="{{ server.config }}" placeholder="{% trans 'extra config' %}">
                    </div>
                    <div class="fix"></div>
                </div>

                <div class="rowElem">
                    <label>{% trans 'Enable/Disable' %}:</label>
                    <div class="formRight">
                        <div class="row pt-3">
                            <div class="col-md-3">
                                <label class="rdiobox">
                                    <input type="radio" name="active" value="1" {% if server.active %}checked="checked"{% endif %}/><span>{% trans 'Enable' %}</span>
                                </label>
                            </div>
                            <div class="col-md-3">
                                <label class="rdiobox">
                                    <input type="radio" name="active" value="0" {% if not server.active %}checked="checked"{% endif %}/><span>{% trans 'Disable' %}</span>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="fix"></div>
                </div>
                <button type="submit" value="" class="btn btn-primary submitForm">{% trans 'Update server' %}</button>
                <button type="button" value="" class="btn btn-info  submitForm" id="test-connection">{% trans 'Test connection' %}</button>


            <input type="hidden" name="server_id" value="{{ server.id }}" />
        </form>
    </div>
</div>

{% endblock %}

{% block js%}
<script type="text/javascript">
    $(function() {

        $('#test-connection').click(function(){
            $('#server-update').submit();
            bb.post('admin/serviceproxmox/server_test_connection', {id:{{server.id}}}, function(result){
                bb.msg('Successfully connected to server');
            });
            return false;
        });

    });
</script>

{% endblock %}
