{% extends "layout_default.phtml" %}
{% block meta_title %}Hosting management{% endblock %}
{% set active_menu = 'system' %}


{% block breadcrumbs %}

    <li class="breadcrumb-item tx-15"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item tx-15"><a  href="{{  'servicehosting'|alink }}">{% trans 'Hosting plans and servers' %}</a></li>
    <li class="breadcrumb-item active">{{ server.name }}</li>

{% endblock %}

{% block content %}

        <form method="post" action="{{ 'api/admin/servicehosting/server_update'|link }}" id="server-update" class="save api-form" data-api-msg="Server updated">
            <div class="card">
                <div class="card-body">
            <div class="rowElem noborder">
                <label>{% trans 'Name' %}:</label>
                <div class="formRight">
                    <input type="text" class="form-control"  name="name" value="{{ server.name }}" required="required" placeholder="Unique name to identify this server">
                </div>
                <div class="fix"></div>
            </div>
            <div class="rowElem">
                <label>{% trans 'Hostname' %}:</label>
                <div class="formRight">
                    <input type="text" class="form-control"  name="hostname" value="{{ server.hostname }}" placeholder="server1.yourserverdomain.com">
                </div>
                <div class="fix"></div>
            </div>
            <div class="rowElem">
                <label>{% trans 'IP' %}:</label>
                <div class="formRight">
                    <input type="text" class="form-control"  name="ip" value="{{ server.ip }}" required="required" placeholder="Primary IP address of the server used to connect to it like: 123.123.123.123">
                </div>
                <div class="fix"></div>
            </div>
            {#
            <div class="rowElem">
                <label>{% trans 'Assigned IP Addresses' %}:</label>
                <div class="formRight">
                    <textarea name="assigned_ips" class="form-control" cols="5" rows="5" placeholder="List the IP Addresses assigned to the server (One per line)">{% for v in server.assigned_ips %}{{ v }}{{constant("PHP_EOL")}}{% endfor %}</textarea>
                </div>
                <div class="fix"></div>
            </div>
            #}
            <div class="rowElem">
                <label>{% trans 'Enable/Disable' %}:</label>
                    <div class="formRight">
                        <div class="formRight">
                            <div class="row pt-3">
                                <div class="col-md-3">
                                    <label class="rdiobox">
                        <input type="radio" name="active" value="1" {% if server.active %}checked="checked"{% endif %}/><span>Yes</span>
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <label class="rdiobox">
                        <input type="radio" name="active" value="0" {% if not server.active %}checked="checked"{% endif %}/><span>No</span>
                                    </label>
                                </div>
                            </div>
                                </div>
                <div class="fix"></div>
            </div>

            </div>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
           <h5>Server manager</h5>
            <div class="rowElem">
                <label>{% trans 'Server manager' %}:</label>
                <div class="formRight">
                    <select name="manager"  class="form-control form-select">
                        {% for code, manager in admin.servicehosting_manager_get_pairs %}
                        <option value="{{code}}" {% if server.manager == code %}selected="selected"{% endif %}>{{ manager.label }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="fix"></div>
            </div>

            <div class="rowElem">
                <label>{% trans 'Username' %}:</label>
                <div class="formRight">
                    <input type="text" class="form-control"  name="username" value="{{ server.username }}" placeholder="Login username to your server: root/reseller">
                </div>
                <div class="fix"></div>
            </div>

            <div class="rowElem">
                <label>{% trans 'Password' %}:</label>
                <div class="formRight">
                    <input type="password" name="password" class="form-control" value="{{ server.password }}" placeholder="Login password to your server">
                </div>
                <div class="fix"></div>
            </div>

            <div class="rowElem">
                <label>{% trans 'Access Hash (Instead of password for cPanel servers)' %}:</label>
                <div class="formRight">
                    <textarea name="accesshash" class="form-control" cols="5" rows="5">{{ server.accesshash }}</textarea>
                </div>
                <div class="fix"></div>
            </div>

            <div class="rowElem">
                <label>{% trans 'Connection port' %}:</label>
                <div class="formRight">
                    <input type="text" class="form-control"  name="port" value="{{ server.port }}" placeholder="Custom port. Use blank to use default. Used to connect to API">
                </div>
                <div class="fix"></div>
            </div>

            <div class="rowElem">
                <label>{% trans 'Use Secure connection' %}:</label>
                    <div class="formRight">
                        <div class="row pt-3">
                            <div class="col-md-3">
                                <label class="rdiobox">
                        <input type="radio" name="secure" value="1" {% if server.secure %}checked="checked"{% endif %}/><span>Yes</span>
                                </label>
                            </div>
                            <div class="col-md-3">
                                <label class="rdiobox">
                                    <input type="radio" name="secure" value="0" {% if not server.secure %}checked="checked"{% endif %}/><span>No</span>
                                </label>
                            </div>
                            </div>
                <div class="fix"></div>
            </div>
        <div class="col-md-12 text-end">
                    <button type="button" value="" class="btn btn-primary submitForm" id="test-connection"><i class="fe fe-save"></i> {% trans 'Update and test connection' %}</button>
        </div>
            </div>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
            <h5>Nameservers</h5>
            <div class="rowElem">
                <label>{% trans 'Nameserver 1' %}:</label>
                <div class="formRight">
                    <input type="text" class="form-control"  name="ns1" value="{{ server.ns1 }}" placeholder="ns1.yourdomain.com">
                </div>
                <div class="fix"></div>
            </div>

            <div class="rowElem">
                <label>{% trans 'Nameserver 2' %}:</label>
                <div class="formRight">
                    <input type="text" class="form-control"  name="ns2" value="{{ server.ns2 }}" placeholder="ns2.yourdomain.com">
                </div>
                <div class="fix"></div>
            </div>

            <div class="rowElem">
                <label>{% trans 'Nameserver 3' %}:</label>
                <div class="formRight">
                    <input type="text" class="form-control"  name="ns3" value="{{ server.ns3 }}" placeholder="ns3.yourdomain.com">
                </div>
                <div class="fix"></div>
            </div>
            <div class="rowElem">
                <label>{% trans 'Nameserver 4' %}:</label>
                <div class="formRight">
                    <input type="text" class="form-control"  name="ns4" value="{{ server.ns4 }}" placeholder="ns4.yourdomain.com">
                </div>
                <div class="fix"></div>
            </div>
            <button type="submit" value="" class="btn btn-primary submitForm"><i class="fe fe-save"></i> {% trans 'Update server' %}</button>


        <input type="hidden" name="id" value="{{ server.id }}" />
                </div>
            </div>
    </form>
    </div>
</div>

{% endblock %}

{% block js%}
<script type="text/javascript">
$(function() {

    $('#test-connection').click(function(){
        $('#server-update').submit();
        bb.post('admin/servicehosting/server_test_connection', {id:{{server.id}}}, function(result){
            bb.msg('Successfully connected to server');
        });
        return false;
    });

});
</script>

{% endblock %}
