{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}{{ tld.tld }}{% endblock %}
{% set active_menu = 'system' %}

{% block breadcrumbs %}

    <li class="breadcrumb-item tx-15"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item tx-15"><a  href="{{  'servicedomain'|alink }}">{% trans 'Domain management' %}</a></li>
    <li class="breadcrumb-item active">{{ tld.tld }}</li>

{% endblock %}


{% block content %}

<div class="card">
    <div class="card-body">
        <h5>{{ tld.tld }} {% trans 'Top level domain management' %}</h5>
        <form method="post" action="{{ 'api/admin/servicedomain/tld_update'|link }}" class="save api-form" data-api-msg="Top level domain settings updated">

            <div class="rowElem noborder">
                <label>{% trans 'Registrar' %}:</label>
                <div class="formRight">
                    <select name="tld_registrar_id" class="form-control form-select" >
                        {% for id, title in admin.servicedomain_registrar_get_pairs %}
                        <option value="{{id}}" {% if id == tld.registrar.id %}selected="selected"{% endif %}>{{ title }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="fix"></div>
            </div>

            <div class="rowElem">
                <label>{% trans 'Registration price' %}:</label>
                <div class="formRight">
                    <input type="text" class="form-control"  name="price_registration" value="{{ tld.price_registration }}" required="required">
                </div>
                <div class="fix"></div>
            </div>

            <div class="rowElem">
                <label>{% trans 'Renewal price' %}:</label>
                <div class="formRight">
                    <input type="text" class="form-control"  name="price_renew" value="{{ tld.price_renew }}" required="required">
                </div>
                <div class="fix"></div>
            </div>

            <div class="rowElem">
                <label>{% trans 'Transfer price' %}:</label>
                <div class="formRight">
                    <input type="text" class="form-control"  name="price_transfer" value="{{ tld.price_transfer }}" required="required">
                </div>
                <div class="fix"></div>
            </div>

            <div class="rowElem">
                <label>{% trans 'Minimum years of registration' %}:</label>
                <div class="formRight">
                    <input type="text" class="form-control"  name="min_years" value="{{ tld.min_years }}" required="required">
                </div>
                <div class="fix"></div>
            </div>

            <div class="rowElem">
                <label>{% trans 'Allow registration' %}:</label>
                <div class="formRight">
                    <div class="row pt-3">
                        <div class="col-md-4">
                            <label class="rdiobox">
                                <input type="radio" name="allow_register" value="1"{% if tld.allow_register %} checked="checked"{% endif %}/> <span>Yes</span>
                            </label>
                        </div>
                        <div class="col-md-4">
                            <label class="rdiobox">
                                <input type="radio" name="allow_register" value="0"{% if not tld.allow_register %} checked="checked"{% endif %} /> <span>No</span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="fix"></div>
            </div>

            <div class="rowElem">
                <label>{% trans 'Allow transfer' %}:</label>
                <div class="formRight">
                    <div class="row pt-3">
                        <div class="col-md-4">
                            <label class="rdiobox">
                                <input type="radio" name="allow_transfer" value="1"{% if tld.allow_transfer %} checked="checked"{% endif %}/> <span>Yes</span>
                            </label>
                        </div>
                        <div class="col-md-4">
                            <label class="rdiobox">
                                <input type="radio" name="allow_transfer" value="0"{% if not tld.allow_transfer %} checked="checked"{% endif %} /> <span>No</span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="fix"></div>
            </div>

            <div class="rowElem">
                <label>{% trans 'Active' %}:</label>
                <div class="formRight">
                    <div class="row pt-3">
                        <div class="col-md-4">
                            <label class="rdiobox">
                                <input type="radio" name="active" value="1"{% if tld.active %} checked="checked"{% endif %}/> <span>Yes</span>
                            </label>
                        </div>
                        <div class="col-md-4">
                            <label class="rdiobox">
                                <input type="radio" name="active" value="0"{% if not tld.active %} checked="checked"{% endif %} /> <span>No</span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="fix"></div>
            </div>


            <input type="hidden" name="tld" value="{{ tld.tld }}" />
            <button type="submit" value="" class="btn btn-primary  submitForm"><i class="fe fe-save"></i> {% trans 'Update' %}</button>

    </form>
    </div>
</div>

{% endblock %}
