{% import "macro_functions.phtml" as mf %}
<div class="help">
    <h5>{% trans 'License settings' %}</h5>
</div>

<form method="post" action="{{ 'api/admin/product/update_config'|link }}" class="api-form save" data-api-msg="License settings updated">
<fieldset>
    <div class="rowElem noborder">
        <label>{% trans 'Prefix' %}:</label>
        <div class="formRight">
            <input type="text" class="form-control"  name="config[prefix]" value="{{ product.config.prefix }}">
        </div>
        <div class="fix"></div>
    </div>
    <div class="rowElem">
        <label>{% trans 'Length' %}:</label>
        <div class="formRight">
            <input type="text" class="form-control"  name="config[length]" value="{{ product.config.length }}">
        </div>
        <div class="fix"></div>
    </div>
    <div class="rowElem">
        <label>{% trans 'Plugin' %}:</label>
        <div class="formRight">
            {{ mf.selectbox('config[plugin]', admin.servicelicense_plugin_get_pairs, product.config.plugin, 1) }}
        </div>
        <div class="fix"></div>
    </div>
    <div class="rowElem">
        <label>{% trans 'Validate IP' %}:</label>
        <div class="formRight">
            <div class="row pt-3">
                <div class="col-md-3">
                    <label class="rdiobox">
                         <input type="radio" name="config[validate_ip]" value="1"{% if product.config.validate_ip %} checked="checked"{% endif %}/><span>Yes</span>
                    </label>
                </div>
                <div class="col-md-3">
                    <label class="rdiobox">
                        <input type="radio" name="config[validate_ip]" value="0"{% if not product.config.validate_ip %} checked="checked"{% endif %} /><span>No</span>
                    </label>
                </div>
            </div>
        </div>
        <div class="fix"></div>
    </div>
    <div class="rowElem">
        <label>{% trans 'Validate Domain' %}:</label>
        <div class="formRight">
            <div class="row pt-3">
                <div class="col-md-3">
                    <label class="rdiobox">
                        <input type="radio" name="config[validate_host]" value="1"{% if product.config.validate_host %} checked="checked"{% endif %}/><span>Yes</span>
                    </label>
                </div>
                <div class="col-md-3">
                    <label class="rdiobox">
                        <input type="radio" name="config[validate_host]" value="0"{% if not product.config.validate_host %} checked="checked"{% endif %} /><span>No</span>
                    </label>
                </div>
            </div>
        </div>
        <div class="fix"></div>
    </div>
    <div class="rowElem">
        <label>{% trans 'Validate Version' %}:</label>
        <div class="formRight">
            <div class="row pt-3">
                <div class="col-md-3">
                    <label class="rdiobox">
                        <input type="radio" name="config[validate_version]" value="1"{% if product.config.validate_version %} checked="checked"{% endif %}/><span>Yes</span>
                    </label>
                </div>

                    <div class="col-md-3">
                        <label class="rdiobox">
                            <input type="radio" name="config[validate_version]" value="0"{% if not product.config.validate_version %} checked="checked"{% endif %} /><span>No</span>
                        </label>
                    </div>
            </div>
        </div>
        <div class="fix"></div>
    </div>
    <div class="rowElem">
        <label>{% trans 'Validate Path' %}:</label>
        <div class="formRight">
            <div class="row pt-3">
                <div class="col-md-3">
                    <label class="rdiobox">
                        <input type="radio" name="config[validate_path]" value="1"{% if product.config.validate_path %} checked="checked"{% endif %}/><span>Yes</span>
                    </label>
                </div>
                <div class="col-md-3">
                    <label class="rdiobox">
                        <input type="radio" name="config[validate_path]" value="0"{% if not product.config.validate_path %} checked="checked"{% endif %} /><span>No</span>
                    </label>
                </div>
            </div>
        </div>
        <div class="fix"></div>
    </div>

    <button type="submit" value="" class="btn btn-primary submitForm"><i class="fe fe-save"></i> {% trans 'Update' %} </button>
</fieldset>

<input type="hidden" name="id" value="{{ product.id }}" />
</form>

