{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% set active_menu = 'order' %}
{% import "macro_functions.phtml" as mf %}

{% block breadcrumbs %}

        <li class="breadcrumb-item tx-15"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
        <li class="breadcrumb-item tx-15"><a  href="{{  'order'|alink }}">{% trans 'Orders' %}</a></li>
        <li class="breadcrumb-item active">{% trans 'Create new order' %}</li>

{% endblock %}

{% block meta_title %}{% trans 'Create new order' %}{% endblock %}

{% block content %}
<div class="card">
    <div class="card-body mt-0">
        <h5 class="iFrames">{% trans 'Create new order' %} "{{ product.title }}" {% trans 'for' %} {{ client.first_name }} {{ client.last_name }}</h5>
        <form method="get" action="{{ 'api/admin/order/create'|link }}" class="api-form" data-api-jsonp="onAfterOrderPlaced">
               <div class="rowElem noborder">
                    <label>{% trans 'Invoice option' %}</label>
                    <div class="formRight noborder">
                        {{ mf.selectbox('invoice_option', admin.order_get_invoice_options, order.invoice_option) }}
                    </div>
                    <div class="fix"></div>
                </div>

                <div class="rowElem">
                    <label>{% trans 'Activate order' %}:</label>
                    <div class="formRight">
                        <div class="row pt-3">
                            <div class="col-md-3">
                                <label class="rdiobox">
                        <input type="radio" name="activate"  value="1" checked="checked"/><span> Yes</span>
                                </label>
                            </div>
                            <div class="col-md-3">
                                <label class="rdiobox">
                        <input type="radio" name="activate" value="0" /><span> No</span>
                                </label>
                            </div>
                    </div>
                    <div class="fix"></div>
                </div>
                {% if product.type == 'hosting' %}
                <div class="rowElem" id="_server_selector_container">
                    <label>Select server:</label>
                    <div class="formRight">
                        <select class="form-control form-select" name="order_server_picked" id="order_server_picked">
                            {% for key, server in admin.order_get_available_servers(product.config) %}
                                <option value="{{key}}">{{server.name}} ({{server.ip}})</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>    
                {% endif %}
                {% if product.pricing.type == 'recurrent' %}
                <div class="rowElem">
                    <label>{% trans 'Period' %}</label>
                    <div class="formRight">
                        <select name="period" id="period" required="required" class="form-control form-select">
                            {% for val,label in guest.system_periods %}
                            <option value="{{ val }}" label="{{ label|e }}" data-price="{{product.pricing.recurrent[val].price}}" data-status="{{product.pricing.recurrent[val].enabled}}" {% if request.period == val %}selected="selected"{% endif %}>{{ label|e }}</option>
                            {% endfor %}
                        </select>
                        <span id="period-info" class="help"></span>
                    </div>
                    <div class="fix"></div>
                </div>
                {% endif %}

                {% set product_order = 'mod_service'~product.type~'_order.phtml' %}
                {% if admin.system_template_exists({"file":product_order}) %}
                    {% include product_order %}
                {% endif %}

                <button type="submit" value="" class="btn btn-primary submitForm btn-form-submit"><i class="fe fe-save"></i> {% trans 'Place new order' %}</button>
                <input type="hidden" name="client_id" value="{{ client.id }}" />
                <input type="hidden" name="product_id" value="{{ product.id }}" />

        </form>
    </div>
</div>

{% endblock %}

{% block js%}
<script type="text/javascript">
    {% if product.type == 'hosting' %}
        $('input[type=radio][name=activate]').on('change', function() {
            if($(this).val() == 0){
                $('#_server_selector_container').slideUp('fast');
            }else{
                $('#_server_selector_container').slideDown('fast');
            }
        });
    {% endif %}
    function onAfterOrderPlaced(id) {
        bb.redirect("{{'order/manage/'|alink}}/"+id);
    }

    $('#period').on('change', function(){
        var optionSelected = $("option:selected", this);
        var periodNotification = $('#period-info');
        var spanElem = $('<span />').css({'padding-left' : '20px', 'line-height' : '28px', 'float' : 'left'});

        periodNotification.text('');
        if (optionSelected.data('price') == 0){
            spanElem.clone().text("{% trans 'Selected price is 0.00'%}").appendTo(periodNotification);
        }
        if (optionSelected.data('status') == 0){
            spanElem.clone().text("{% trans 'Product is disabled in configuration'%}").appendTo(periodNotification);
        }

    });

</script>
{% endblock %}
