{% extends "layout_login.phtml" %}

{% block meta_title %}{% trans 'Login' %}{% endblock %}

{% block content %}
<div id="global-loader">
    <img src="img/loader.svg" class="loader-img" alt="Loader">
</div>
<div class="square-box">
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
</div>
<div class="page" >
    <div class="page-single">
        <div class="container">
            <div class="row">
                <div class="col-xl-5 col-lg-6 col-md-8 col-sm-8 col-xs-10 card-sigin-main mx-auto my-auto py-4 justify-content-center">
                    <div class="card-sigin">
                        <!-- Demo content-->
                        <div class="main-card-signin d-md-flex">
                            <div class="wd-100p"><div class="d-flex mb-4"><a href="index.html"><img src="https://control-webpanel.com/wp-content/uploads/2020/04/3d_logo_200x55.png" class="sign-favicon" alt="logo"></a></div>
                                <div class="">
                                    <div class="main-signup-header">
                                        <!--<h2>Welcome back!</h2>-->
                                        <!--<h6 class="font-weight-semibold mb-4">Please sign in to continue.</h6>-->
                                        <div class="alert alert-primary alert-recover-pass"><h5>Enter your email to reset password. You will receive new password after reset link is confirmed.</h5></div>
                                        <div class="panel panel-primary">
                                            <!--<div class=" tab-menu-heading mb-2 border-bottom-0">
                                                <div class="tabs-menu1">
                                                    <ul class="nav panel-tabs">
                                                        <li class="me-2"><a href="#tab5" class="active" data-bs-toggle="tab">Email</a></li>
                                                        <li><a href="#tab6" data-bs-toggle="tab" class="">Mobile no</a></li>
                                                    </ul>
                                                </div>
                                            </div>-->
                                            <div class="panel-body tabs-menu-body border-0 p-3">
                                                <div class="tab-content">
                                                    <div class="tab-pane active" id="tab5">
                                                        <form class="mainForm api-form" action="{{ 'api/guest/staff/recover_password'|link }}" method="post" data-api-redirect="{{ 'index'|alink }}">
                                                            <div class="form-group">
                                                                <label>Email</label> <input class="form-control" id="req1" required="required" type="email" name="email" value="{{ request.email }}" placeholder="{% trans 'Enter your email address' %}" autofocus>
                                                            </div>
                                                            <button type="submit" class="btn btn-primary btn-block btn-form-submit"><i class="fa fa-retweet"></i> Reset password</button>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .alert-recover-pass{
        margin-bottom: 0px;
    }
    .alert-recover-pass h5{
        font-size: 1rem;
    }
</style>
<!--    </div>
</div>-->
<script src="js/plugins/jquery/jquery.min.js"></script>

<!-- Bootstrap js -->
<script src="js/plugins/bootstrap/js/popper.min.js"></script>
<script src="js/plugins/bootstrap/js/bootstrap.min.js"></script>

<!-- Ionicons js -->
<script src="js/plugins/ionicons/ionicons.js"></script>

<!-- Moment js -->
<script src="js/plugins/moment/moment.js"></script>

<!-- eva-icons js -->
<script src="js/eva-icons.min.js"></script>

<!-- generate-otp js -->
<script src="js/generate-otp.js"></script>

<!--Internal  Perfect-scrollbar js -->
<script src="js/plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>

<!-- Theme Color js -->
<script src="js/themecolor.js"></script>

<!-- custom js -->
<script src="js/custom.js"></script>

{% endblock %}
