{% extends "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}Tax{% endblock %}
{% set active_menu = 'system' %}

{% block content %}
<div class="card">
    <div class="card-body">

           <!-- <div class="tab_content nopadding" id="tab-new">-->

                <form method="post" action="{{ 'api/admin/invoice/tax_update'|link }}" data-api-redirect="{{ 'invoice/tax'|alink }}" class="save api-form">

                        <div class="rowElem noborder">
                            <label>{% trans 'Tax title' %}:</label>
                            <div class="formRight">
                                <input type="text" class="form-control" name="name" value="{{tax.name}}" required="required" placeholder="{% trans 'sales Tax' %}"/>
                            </div>
                            <div class="fix"></div>
                        </div>
                        <div class="rowElem">
                            <label>{% trans 'Tax rate' %}:</label>
                            <div class="formRight">
                                <input type="text" class="form-control" name="taxrate" value="{{tax.taxrate}}" required="required" placeholder="{% trans '18' %}" style="width: 100px"/> %
                            </div>
                            <div class="fix"></div>
                        </div>
                        <div class="rowElem">
                            <label>{% trans 'Country' %}:</label>
                            <div class="formRight">
                                {{ mf.selectbox('country', guest.system_countries, tax.country, 0, 'Apply to all countries') }}
                            </div>
                            <div class="fix"></div>
                        </div>
                        <div class="rowElem">
                            <label>{% trans 'State' %}:</label>
                            <div class="formRight">
                                {# mf.selectbox('state', guest.system_states, tax.state, 0, 'Apply to all states') #}
                                <input type="text" class="form-control" name="state" value="{{ tax.state }}" placeholder="{% trans 'Leave empty to apply to all states' %}"/>
                            </div>
                            <div class="fix"></div>
                        </div>
                        <input type="hidden" name="id" value="{{ tax.id }}"/>
                    <button type="submit" value="" class="btn btn-primary submitForm"><i class="fe fe-save"></i> {% trans 'Update' %}</button>

                </form>
           <!-- </div> -->
    </div>
</div>
{% endblock %}
