{% extends "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}

{% block meta_title %}{% trans 'Profile' %}{% endblock %}
{% set active_menu = 'system' %}


{% block breadcrumbs %}

    <li class="breadcrumb-item tx-15"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item tx-15"><a  href="{{  'system'|alink }}">{% trans 'Settings' %}</a></li>
    <li class="breadcrumb-item tx-15"><a  href="{{  'extension/settings/staff'|alink }}">{% trans 'Staff' %}</a></li>
    <li class="breadcrumb-item active">{{staff.name}}</li>

{% endblock %}

{% block content %}

{% if staff.role == 'cron' %}
<div class="nNote nInformation hideit first">
    <p><strong>{% trans 'INFORMATION' %}: </strong>{% trans 'This staff member is used by WebHosting Billing to perform system tasks and can not be removed.' %}</p>
</div>
{% endif %}
<div class="card">
    <div class="card-body mt-0">
        <div class="panel panel-primary tabs-style-2">
            <div class=" tab-menu-heading">
                <div class="tabs-menu1">

                    <ul class="nav panel-tabs main-nav-line">
                        <li><a class="nav-link active" data-bs-toggle="tab" href="#tab-profile">{% trans 'Profile' %}</a></li>
                        <li><a  class="nav-link" data-bs-toggle="tab" href="#tab-permissions">{% trans 'Permissions' %}</a></li>
                        <li><a  class="nav-link" data-bs-toggle="tab" href="#tab-password">{% trans 'Password' %}</a></li>
                        <li><a  class="nav-link" data-bs-toggle="tab" href="#tab-2fa">{% trans 'Two Factor Authenticator' %}</a></li>
                        <li><a  class="nav-link" data-bs-toggle="tab" href="#tab-api">{% trans 'API' %}</a></li>
                    </ul>
                </div>
            </div>

        <div class="panel-body tabs-menu-body main-content-body-right border">
            <div class="tab-content">
                <div class="tab-pane active"  id="tab-profile">
                    <div class="help">
                        <h5>{% trans 'Manage staff member details' %}</h5>
                    </div>
                    <form method="post" action="admin/staff/update" class="api-form" data-api-msg="{% trans 'This staff member updated.' %}">

                            <div class="rowElem noborder">
                                <label>{% trans 'Group' %}</label>
                                <div class="formRight">
                                    {{ mf.selectbox('admin_group_id', admin.staff_group_get_pairs, staff.group.id, 1) }}
                                </div>
                                <div class="fix"></div>
                            </div>
                            <div class="rowElem">
                                <label for="name">{% trans 'Name' %}</label>
                                <div class="formRight">
                                    <input type="text" class="form-control"  name="name" value="{{staff.name}}" required="required"/>
                                </div>
                                <div class="fix"></div>
                            </div>
                            <div class="rowElem">
                                <label for="email">{% trans 'Email' %}</label>
                                <div class="formRight">
                                    <input type="text" class="form-control"  name="email" value="{{staff.email}}" required="required"/>
                                </div>
                                <div class="fix"></div>
                            </div>
                            <div class="rowElem">
                                <label>{% trans 'Status' %}</label>
                                <div class="formRight">
                                    <div class="row pt-3">
                                        <div class="col-md-3">
                                            <label class="rdiobox">
                                                <input type="radio" name="status" value="active"{% if staff.status == 'active' %} checked="checked"{% endif %}/><span>Active</span>
                                            </label>
                                        </div>
                                        <div class="col-md-3">
                                            <label class="rdiobox">
                                                <input type="radio" name="status" value="inactive"{% if staff.status == 'inactive' %} checked="checked"{% endif %} /><span>Inactive</span>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="fix"></div>
                            </div>
                            <div class="rowElem">
                                <label for="signature">{% trans 'Signature' %}</label>
                                <div class="formRight">
                                    <textarea class="form-control" name="signature" cols="5" rows="2">{{staff.signature}}</textarea>
                                </div>
                                <div class="fix"></div>
                            </div>
                            <input type="hidden" name="id" value="{{ staff.id }}">
                            <button type="submit" value="" class="btn btn-primary  submitForm"><i class="fe fe-save"></i> {% trans 'Update' %}</button>

                    </form>
                </div>
                <div id="tab-permissions" class="tab-pane">
                    <div class="help">
                        {% set member_name = staff.name %}
                        <h5>{% trans %}{{ member_name }} permissions{% endtrans %}</h5>
                    </div>

                    {% if staff.role == 'admin' %}
                    <div class="body">
                        <p>{% trans 'Administrator account is allowed to do everything' %}</p>
                    </div>
                    {% else %}
                    {% set prms = admin.staff_permissions_get({"id":staff.id}) %}
                    <form method="post" action="admin/staff/permissions_update" class="api-form" data-api-msg="{% trans 'Permissions updated' %}">
                    <input type="hidden" name="permissions[]" value="">

                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <td style="width: 5%">
                                    <input type="checkbox" id="perm-check" />
                                </td>
                                <td>{% trans 'Module' %}</td>
                            </tr>
                        </thead>

                        <tbody>
                        {% for mod in mods %}
                        <tr>
                            <td>
                                <input type="checkbox" name="permissions[{{mod}}]" value="1" class="perm" {% if prms[mod] %}checked="checked"{% endif %}/>
                            </td>
                            <td>{{mod|title}}</td>
                        </tr>
                        {% endfor %}
                        </tbody>

                    </table>
                        <div class="text-end col-md-12">
                            <input type="hidden" name="id" value="{{ staff.id }}">
                            <button type="submit" value="" class="btn btn-primary "><i class="fe fe-save"></i> {% trans 'Save' %}</button>
                        </div>
                    </form>
                    {% endif %}
                </div>
                <div id="tab-password" class="tab-pane">
                    <div class="help">
                        <h5>{% trans 'Change staff member password' %}</h5>
                    </div>

                    <form method="post" action="admin/staff/change_password" class="api-form" data-api-msg="{% trans 'Staff member password changed' %}">

                            <div class="rowElem noborder">
                                <label for="password">{% trans 'Password' %}</label>
                                <div class="formRight">
                                    <input type="password" class="form-control"  name="password" required="required"/>
                                </div>
                                <div class="fix"></div>
                            </div>
                            <div class="rowElem">
                                <label for="password_confirm">{% trans 'Repeat same password' %}</label>
                                <div class="formRight">
                                    <input type="password" class="form-control"  name="password_confirm" required="required"/>
                                </div>
                                <div class="fix"></div>
                            </div>

                            <input type="hidden" name="id" value="{{ staff.id }}">
                            <button type="submit" value="" class="btn btn-primary submitForm"><i class="fe fe-save"></i> {% trans 'Submit' %}</button>

                    </form>
                </div>
                <div id="tab-2fa" class="tab-pane">
                    <div class="help">
                        <h5>{% trans 'Google Two Factor Authentication' %}</h5>
                        <p>{% trans 'Two Factor Authentication protects information from possible hacks and scares hackers away. Besides this even though your login credentials are leaked by accident, it protects your account.' %}</p>
                    </div>
                    <!---->
                    <form method="post" action="admin/staff/update_2fa" class="api-form" data-api-reload="1">

                        <div class="twofa-status-changer">
                            <label>{% trans 'Google Two Factor Authentication status:' %}</label>
                            <select name="twofactor_status" class="form-control form-select" onchange="changeTwoFactorSelect(this)">
                                <option value="disabled" selected="">Disabled</option>
                                <option value="enabled">Enabled</option>
                            </select>
                            <div class="fix"></div>
                        </div>
                        <input type="hidden" name="id" value="{{ staff.id }}">
                        <button type="submit" value="" class="btn btn-primary submitForm"><i class="fe fe-save"></i> {% trans 'Update' %}</button>

                    </form>
                </div>

                <div id="tab-api" class="tab-pane">
                    <div class="help">
                        <h5>{% trans 'API Key' %}</h5>
                    </div>

                    <form method="post" action="admin/profile/generate_api_key" class="api-form" data-api-reload="1">

                        <div class="rowElem noborder">
                            <label>{% trans 'API key' %}</label>
                            <div class="formRight">
                                <input type="text" class="form-control"  value="{{ admin.profile_get.api_token }}"/>
                            </div>
                            <div class="fix"></div>
                        </div>
                        <input type="hidden" name="id" value="{{ staff.id }}">
                        <button type="submit" value="" class="btn btn-primary submitForm"><i class="fe fe-save"></i> {% trans 'Generate new key' %}</button>

                    </form>

                </div>
            </div>
            <div class="fix"></div>
        </div>
        </div>
    </div>
</div>
{% endblock %}


{% block js%}
<script type="text/javascript">

$(function() {
    $('#perm-check').click(function(){
        if($('#perm-check').is(':checked')) {
            $('.perm').prop('checked', true);
        } else {
            $('.perm').prop('checked', false);
        }
        $.uniform.update(".perm");
    });
});

</script>
{% endblock %}
