{% extends "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% set active_menu = 'products' %}
{% block meta_title %}{{ category.title}}{% endblock %}


{% block breadcrumbs %}

    <li class="breadcrumb-item tx-15"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item tx-15"><a  href="{{  'product'|alink }}">{% trans 'Products' %}</a></li>
    <li class="breadcrumb-item tx-15"><a  href="{{  'product'|alink }}#tab-categories">{% trans 'Categories' %}</a></li>
    <li class="breadcrumb-item active">{{ category.title}}</li>

{% endblock %}

{% block content %}
<div class="card">
    <div class="card-body mt-0">
        <form method="post" action="{{ 'api/admin/product/category_update'|link }}" class="save api-form" data-api-msg="{% trans 'Category updated' %}">
        <fieldset>
            <div class="rowElem noborder">
                <label>{% trans 'Title' %}:</label>
                <div class="formRight">
                    <input type="text" class="form-control" name="title" value="{{ category.title }}" required="required"/>
                </div>
                <div class="fix"></div>
            </div>

            <div class="rowElem">
                <label>{% trans 'Icon' %}:</label>
                <div class="formRight">
                    <input type="text" name="icon_url" class="form-control"  id="bb-icon" value="{{ category.icon_url }}" style="width: 80%"/>
                    <input type="button" value="{% trans 'Browse' %}" class="bHtml btn btn-info button" />
                </div>
                <div class="fix"></div>
            </div>
            <label>{% trans 'Description' %}:</label>

            <textarea name="description" cols="5"  rows="20" class="form-control">{{ category.description }}</textarea>

            <button type="submit" value="" class="btn btn-primary submitForm"><i class="fe fe-save"></i> {% trans 'Update' %} </button>
            <input type="hidden" name="id" value="{{ category.id }}"/>
        </fieldset>
    </form>
    </div>
</div>

{% endblock %}

{% block head %}{{ mf.bb_editor('.bb-textarea') }}{% endblock %}

{% block js %}
<script type="text/javascript">
$(function() {
	$(".bHtml").click( function() {
        let datos = bb.load('{{"filemanager/icons"|alink }}', {rel:"bb-icon"});
        $("#scrollmodal").modal('show');
        $("#scrollmodal .modal-body").html(datos);
        $("#scrollmodal .modal-title").html( "{% trans 'Select icon and click OK' %}");
		//jAlert(bb.load('{{"filemanager/icons"|alink }}', {rel:"bb-icon"}), '{% trans 'Select icon and click OK' %}');
	});
});
</script>
{% endblock %}
