{% extends "layout_default.phtml" %}
{% set active_menu = 'client' %}
{% block meta_title %}{{ group.title}}{% endblock %}

{% block breadcrumbs %}

    <li class="breadcrumb-item tx-15"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item tx-15"><a  href="{{  'client'|alink }}#tab-groups">{% trans 'Client groups' %}</a></li>
    <li class="breadcrumb-item active">{{ group.title}}</li>

{% endblock %}


{% block content %}
<div class="widget">

    <div class="head">
        <h5>{{ group.title}}</h5>
    </div>

    <form method="post" action="{{ 'api/admin/client/group_update'|link }}" class="save api-form" data-api-redirect="{{ 'client'|alink }}">
        <fieldset>
            <div class="rowElem noborder">
                <label>{% trans 'Title' %}:</label>
                <div class="formRight">
                    <input type="text" class="form-control" name="title" value="{{ group.title }}" required="required"/>
                </div>
                <div class="fix"></div>
            </div>

            <button type="submit" value="" class="btn btn-primary submitForm"><i class="fe fe-save"></i> {% trans 'Update' %} </button>
            <input type="hidden" name="id" value="{{ group.id }}"/>
        </fieldset>
    </form>
</div>

{% endblock %}
