{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}{% trans 'Extensions' %}{% endblock %}
{% set active_menu = 'extensions' %}

{% block content %}

<div class="card mg-b-20" id="tabs-style2">
    <!--<div class="card-body">-->
    <div class="text-wrap">
        <div class="example">
            <div class="panel panel-primary tabs-style-2">
                <div class=" tab-menu-heading">
                    <div class="tabs-menu1">
                        <!-- Tabs -->
                        <ul class="nav panel-tabs main-nav-line">
                            <li><a href="#tab-index" class="nav-link active" data-bs-toggle="tab">{% trans 'Extensions' %}</a></li>
                            <li><a href="#tab-core" class="nav-link" data-bs-toggle="tab">{% trans 'Update WebHosting Billing' %}</a></li>
                            <li><a href="#tab-about" class="nav-link" data-bs-toggle="tab">{% trans 'Learn more about extensions' %}</a></li>
                            <li><a href="#tab-hooks" class="nav-link" data-bs-toggle="tab">{% trans 'Hooks' %}</a></li>
                        </ul>
                    </div>
                </div>
                <div class="panel-body tabs-menu-body main-content-body-right border">
                    <div class="tab-content">
                        <div class="tab-pane  active" id="tab-index">
                            <div class="help">
                                <h5>WebHosting Billing extensions</h5>
                                <p>{% trans %}Activate or deactivate extensions{% endtrans %}</p>
                            </div>
                            <div class="table-responsive">
                                <table class="table table-bordered text-nowrap border-bottom" id="tableExtension">
                                    <thead>
                                        <tr>
                                            <td width="3%">&nbsp;</td>
                                            <td width="20%">{% trans 'Extension' %}</td>
                                            <td>{% trans 'Description' %}</td>
                                            <td style="width: 21%;">{% trans 'Actions' %}</td>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        {% for ext in admin.extension_get_list %}
                                        <tr>
                                            <td><img src="{{ ext.icon_url|default('images/icons/middlenav/cog.png') }}" alt="{{ext.name}}" style="width: 25px; height: 25px;"/></td>
                                            <td><strong>{{ ext.name }}</strong> {{ ext.version }}<br />by <a href="{{ ext.author_url }}" target="_blank">{{ ext.author }}</a></td>
                                            <td>
                                                {{ ext.description|bbmd }}
                                                <a href="{{ ext.project_url }}" class="btn text-info bg-info-transparent btn-sm" target="_blank" title="Project details">Learn more</a>
                                            </td>
                                            <td>
                                                {% if ext.type == 'mod' %}
                                                {% if ext.status == 'installed' %}
                                                <a class="api-link btn text-danger bg-danger-transparent btn-sm mb-1" href="{{ 'api/admin/extension/deactivate' |link({'type' : ext.type, 'id' : ext.id}) }}" data-api-confirm="Are you sure?" data-api-reload="Module was deactivated" title="{% trans 'Deactivate' %}"><i class="fe fe-eye-off"></i></a>
                                                {% else %}
                                                <a class="btn text-primary bg-primary-transparent btn-sm mb-1api-link" href="{{ 'api/admin/extension/activate' |link({'type' : ext.type, 'id' : ext.id}) }}" data-api-confirm="Are you sure?" data-api-jsonp="onAfterModuleActivated"><i class="fe fe-settings"></i><span>  Activate</span></a>
                                                {% endif %}
                                                {% else %}
                                                &nbsp;
                                                {% endif %}

                                                {% if ext.has_settings %}
                                                <a class="btn text-warning bg-warning-transparent btn-sm mb-1" href="{{ 'extension/settings'|alink }}/{{ext.id}}"><i class="fe fe-edit-2"></i><!--<img src="images/icons/dark/pencil.png" alt="" class="icon" title="{% trans 'Module settings' %}">--></a>
                                                {% endif %}
                                            </td>
                                        </tr>
                                        {% else %}
                                        <tr>
                                            <td colspan="4">
                                                {% trans 'The list is empty' %}
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <td colspan="4"></td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                            <div class="help">
                                <h5>WebHosting Billing modules on extension site</h5>
                            </div>
                            {% include "partial_extensions.phtml" %}
                        </div>
                        <div class="tab-pane" id="tab-core">
                            <div class="help">
                                <h3>{% trans 'Automatic update' %}</h3>
                                <p>{% trans %}Automatic updater is a tool to update WebHosting Billing to latest version in one click. Works on these hosting environments where PHP has permissions to overwrite files uploaded via FTP.{% endtrans %}</p>
                            </div>

                            <div class="body">
                                <a href="{{ 'api/admin/extension/update_core'|link }}" title="" class="btn btn-primary btn-sm mb-1 api-link" data-api-confirm="Make sure that you have made database and files backups before proceeding with automatic update. Click OK when you are ready to continue." data-api-msg="Update complete"><i class="fe fe-settings"></i><span>  Update WebHosting Billing</span></a>
                            </div>

                            <div class="help">
                                <h3>{% trans %}Manual update{% endtrans %}</h3>
                                <p>{% trans %}Manual update is a solution when auto updater can not work on current installation environment{% endtrans %}</p>
                            </div>

                            <div class="body list arrowGreen">
                                <ul>
                                    <li>Download latest WebHosting Billing from <a href="https://github.com/boxbilling/boxbilling/releases" target="_blank">Our Github</a></li>
                                    <li>Extract files at your computer</li>
                                    <li>Upload (overwrite) extracted files via FTP to <strong>{{ constant('BB_PATH_ROOT') }}</strong></li>
                                    <li>When upload is complete, execute <a href="{{constant('BB_URL')}}bb-update.php" target="_blank">{{constant('BB_URL')}}bb-update.php</a> in your browser</li>
                                    <li>Your WebHosting Billing is now updated to latest version.</li>
                                </ul>
                            </div>
                        </div>
                        <div class="tab-pane" id="tab-about">
                            <div class="help">
                                <h3>{% trans 'Extending WebHosting Billing' %}</h3>
                                <p>{% trans %}WebHosting Billing gives developers all the capabilities to customize, integrate & extend the core system into your own website & applications.{% endtrans %}</p>
                            </div>
                            <div class="body">
                                <h2 class="pt20">More extensions</h2>
                                <p>If you can not find extensions you are looking for in this admin area, please visit extensions site at <a href="http://extensions.boxbilling.com" target="_blank">http://extensions.boxbilling.com</a></p>

                                <h2 class="pt20">How to create new extension</h2>
                                <div class="pt20 list arrowGrey">
                                    <ul>
                                        <li>Create free account at <a href="https://github.com/signup/free" target="_blank">Github</a></li>
                                        <li>Create new public repository dedicated for extension only</li>
                                        <li>Repository must have plugin json file. <a href="http://extensions.boxbilling.com/article/getting-started" target="_blank">More information</a></li>
                                        <li>Login to <a href="http://extensions.boxbilling.com/" target="_blank">WebHosting Billing extensions site</a> with github account.</li>
                                        <li>If your repository contains valid json file, it can be registered in extensions site.</li>
                                        <li>Registered extensions can be visible in every WebHosting Billing admin area.</li>
                                    </ul>
                                </div>

                                <h2 class="pt20">Supported extension types</h2>
                                <div class="pt20 list arrowGrey">
                                    <ul>
                                        <li>Payment gateways</li>
                                        <li>Server managers</li>
                                        <li>Domain registrars</li>
                                        <li>Client area themes</li>
                                        <li>Admin area themes</li>
                                        <li>Translations for client and admin areas</li>
                                        <li>Event hooks - Hooks can be injected into the process, change its behaviour, stop executing actions</li>
                                        <li>API module - External program which uses WebHosting Billing API</li>
                                    </ul>
                                </div>

                                <h2 class="pt20">Extension support</h2>
                                <p>Contact extensions developers directly for support. You can find issue tracker on extension site.</p>
                            </div>
                        </div>
                        <div class="tab-pane" id="tab-hooks">
                            <div class="table-responsive">
                                <table class="table table-bordered text-nowrap border-bottom" id="tableExpExtension">
                                    <thead>
                                        <tr>
                                            <td>{% trans 'Extension' %}</td>
                                            <td>{% trans 'Hook' %}</td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for hook in admin.hook_get_list({"per_page":90}).list %}
                                        <tr>
                                            <td>
                                                {{ hook.rel_id | capitalize}}
                                            </td>
                                            <td>
                                                {{ hook.event }}
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--</div>-->
</div>


{% endblock %}

{% block js %}
<script type="text/javascript">
    //tableExtension
    $(document).ready(function() {
        $('#tableExtension').dataTable( {
            "searching": true
        } );
        $('#tableExtension2').dataTable( {
            "searching": true
        } );
    } );
    function onAfterUpdate(result) {

    }

    function onAfterModuleActivated(result) {
        if(result.redirect && result.type == 'mod') {
            bb.redirect("{{ '' | alink}}/" + result.id);
        } else if(result.has_settings) {
            bb.redirect("{{ 'extension/settings'|alink }}/"+result.id);
        } else {
            bb.reload();
        }
    }
</script>
{% endblock %}
