{% extends "layout_default.phtml" %}
{% block meta_title %}Client area languages{% endblock %}
{% set active_menu = 'extensions' %}

{% block content %}
<div class="card">
    <div class="card-body mt-0">
        <div class="panel panel-primary tabs-style-2">
            <div class=" tab-menu-heading">
                <div class="tabs-menu2">

                    <ul class="nav panel-tabs main-nav-line">
                        <li><a class="nav-link active" data-bs-toggle="tab" href="#tab-index">{% trans 'Client area languages' %}</a></li>
                        <li><a class="nav-link" data-bs-toggle="tab" href="#tab-new">{% trans 'New language' %}</a></li>
                    </ul>
                </div>
            </div>
            <div class="panel-body tabs-menu-body main-content-body-right border">
                <div class="tab-content">
                    <div class="tab-pane active"id="tab-index">
                        <table id="tableLanguage" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <td>{% trans 'Language' %}</td>
                                    <td>{% trans 'Code' %}</td>
                                </tr>
                            </thead>

                            <tbody>
                            {% for lang in admin.extension_languages %}
                            <tr>
                                <td>{{ lang.title }}</td>
                                <td style="width: 10%">{{ lang.locale }}</td>
                            </tr>
                            </tbody>

                            {% else %}
                            <tbody>
                                <tr>
                                    <td colspan="2">
                                        {% trans 'The list is empty' %}
                                    </td>
                                </tr>
                            </tbody>
                            {% endfor %}
                        </table>
                    </div>

                    <div class="tab-pane" id="tab-new">
                        {% include "partial_extensions.phtml" with {'type': 'translation', 'header':"List of translations on extensions site"} only %}

                        <div class="alert alert-success mb-2" role="alert">
                            <h4 class="alert-heading"><i class="fe fe-check-circle me-2 tx-20"></i>{% trans 'WebHosting Billing in your language' %}</h4>
                            <p>{% trans %}Although WebHosting Billing displays in U.S. English by default, the software has the built-in capability to be used in any language. Follow instructions bellow to install new language.{% endtrans %}</p>
                            <hr>
                            <p class="mb-0">
                            <ul>
                                <li>{% trans %}Check if your language translation file is available at{% endtrans %} <a href="https://www.transifex.com/projects/p/boxbilling/" target="_blank">{% trans %}WebHosting Billing translations repository{% endtrans %}</a></li>
                                <li>{% trans %}Download language files and place them to{% endtrans %} <strong>{{ constant('BB_PATH_LANGS') }}</strong></li>
                                <li>{% trans %}Language will be automatically available and can be changed in client area{% endtrans %}</li>
                                <li>{% trans %}Read{% endtrans %} <a href="http://docs.boxbilling.com/en/latest/reference/language.html" title="Installing WebHosting Billing in Your Language" target="_blank">{% trans %}Installing WebHosting Billing in Your Language{% endtrans %}</a> {% trans %}to learn how to install files that will transform WebHosting Billing so it displays in your language.{% endtrans %}</li>
                                <li>{% trans %}Translations can be made with{% endtrans %} <a href="http://www.poedit.net/" target="_blank">http://www.poedit.net/</a> {% trans %}software{% endtrans %}</li>
                            </ul>
                            <h5 class="pt20">{% trans 'Changing default language' %}</h5>
                            <p>{% trans %}Default language can be set in{% endtrans %} <em>bb-config.php</em> parameter <strong>define('BB_LOCALE', 'en_US');</strong></p>

                            <h5 class="pt20">{% trans 'Removing language' %}</h5>
                            <p>{% trans %}Removing languages from WebHosting Billing is really simple. Just delete language folder you wish from{% endtrans %} <strong>{{ constant('BB_PATH_LANGS') }}</strong></p>

                            </p>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
       $("#tableLanguage").DataTable();
    });
</script>
{% endblock %}
