{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}Clients login history{% endblock %}
{% set active_menu = 'activity' %}

{% block content %}
<div class="card">
    <div class="card-body">

        <table id="tableStaff" class="table table-striped table-bordered">
            <thead>
                <tr>
                    <td style="width: 2%"><input type="checkbox" class="batch-delete-master-checkbox"/></td>
                    <td >{% trans 'Client' %}</td>
                    <td>{% trans 'IP' %}</td>
                    <td>{% trans 'Country' %}</td>
                    <td>{% trans 'Date' %}</td>
                    <td style="width: 5%">&nbsp;</td>
                </tr>
            </thead>

            <tbody>
            {% set history = admin.client_login_history_get_list({"per_page":1000000, "page":request.page}|merge(request)) %}
            {% for i, event in history.list %}
            <tr>
                <td><input type="checkbox" class="batch-delete-checkbox" data-item-id="{{ event.id }}"/></td>
                <td style="width:5%"><a href="{{ 'client/manage'|alink }}/{{ event.client.id }}"><img src="{{ event.client.email|gravatar }}?size=20" alt="{{ event.client.email }}" class="avatar-md rounded-circle me-3 my-auto shadow" /></a>
                    {{ event.client.first_name }} {{ event.client.last_name }}</td>
                <td>{{ event.ip }}</td>
                <td>{{ event.ip|ipcountryname|default('Unknown') }}</td>
                <td>{{ event.created_at|date('Y-m-d H:i') }}</td>
                <td class="actions">
                    <a class="btn btn-sm  bg-danger-transparent text-danger bb-rm-tr api-link" data-api-confirm="Are you sure?" data-api-redirect="{{ 'client/logins'|alink }}" href="{{ 'api/admin/client/login_history_delete'|link({'id' : event.id}) }}"><i class="fe fe-trash"></i></a>
                </td>
            </tr>
            {% endfor %}
            </tbody>

        </table>
        {% include "partial_batch_delete.phtml" with {'action' : 'admin/client/batch_delete_log'} %}
    </div>
</div>
<script>
    $(document).ready(function(){
        $("#tableStaff").DataTable();
    });
</script>
{% endblock %}
