<div class=" tab-menu-heading">
    <div class="tabs-menu1">
        <ul class="nav panel-tabs main-nav-line">
            <li><a class="nav-link active" data-bs-toggle="tab" href="#tab-stock">{% trans 'Stock control settings' %}</a></li>
            <li><a class="nav-link" data-bs-toggle="tab" href="#tab-plugins">{% trans 'Plugin' %}</a></li>
            <li><a class="nav-link" data-bs-toggle="tab" href="#tab-custom_parameters">Custom parameters</a></li>
        </ul>
    </div>
</div>



<div class="panel-body tabs-menu-body main-content-body-right border">
    <form method="post" action="admin/product/update" class="api-form save" data-api-msg="Product configuration updated" name="form">
        <div class="tab-content">
            <div class="tab-pane active" id="tab-stock">
                <!--<div class="help">
                    <h5>{% trans 'Stock control settings' %}</h5>
                </div>-->
                <form method="post" action="{{ 'api/admin/product/update'|link }}" class="api-form save" data-api-msg="Settings updated">
                    <fieldset>
                        <div class="rowElem noborder">
                            <label>{% trans 'Enable stock control' %}:</label>
                            <div class="formRight">
                                <div class="row pt-3">
                                    <div class="col-md-3">
                                        <label class="rdiobox">
                                            <input type="radio" name="stock_control" value="1"{% if product.stock_control %} checked="checked"{% endif %}/>
                                            <span for="status-enabled">Yes</span>
                                        </label>
                                    </div>
                                    <div class="col-md-3">
                                        <label class="rdiobox">
                                            <input type="radio" name="stock_control" value="0"{% if not product.stock_control %} checked="checked"{% endif %} />
                                            <span for="status-disabled">No</span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="fix"></div>
                        </div>
                        <div class="rowElem">
                            <label>{% trans 'Allow quantity select on order form' %}:</label>
                            <div class="formRight">
                                <div class="row pt-3">
                                    <div class="col-md-3">
                                        <label class="rdiobox">
                                            <!--<input type="radio" name="status" value="enabled" checked="checked" id="status-enabled">-->
                                            <input type="radio" name="allow_quantity_select" value="1"{% if product.allow_quantity_select %} checked="checked"{% endif %}/>
                                            <span for="status-enabled">Yes</span>
                                        </label>
                                    </div>
                                    <div class="col-md-3">
                                        <label class="rdiobox">
                                            <!--<input type="radio" name="status" value="disabled" id="status-disabled">-->
                                            <input type="radio" name="allow_quantity_select" value="0"{% if not product.allow_quantity_select %} checked="checked"{% endif %} />
                                            <span for="status-disabled">No</span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="fix"></div>
                        </div>
                        <div class="rowElem">
                            <label>{% trans 'Quantity in stock' %}:</label>
                            <div class="formRight">
                                <input type="text" class="form-control" name="quantity_in_stock" value="{{ product.quantity_in_stock }}">
                            </div>
                            <div class="fix"></div>
                        </div>
                        <button type="submit" value="" class="btn btn-primary  submitForm"><i class="fe fe-save"></i> {% trans 'Update' %}</button>
                    </fieldset>
                    <input type="hidden" name="id" value="{{ product.id }}" />
                </form>
            </div>
            <div class="tab-pane " id="tab-plugins">
                <!--<div class="help">
                    <h5>{% trans 'Plugin' %}</h5>
                </div>-->

                <form method="post" action="{{ 'api/admin/product/update'|link }}" class="api-form save" data-api-msg="Settings updated">
                    <fieldset>
                        <div class="rowElem noborder">
                            <label>{% trans 'Plugin name' %}:</label>
                            <div class="formRight">
                                <input type="text" class="form-control" name="plugin" value="{{ product.plugin }}"/>
                            </div>
                            <div class="fix"></div>
                        </div>

                        <button type="submit" value="" class="btn btn-primary  submitForm"><i class="fe fe-save"></i> {% trans 'Update' %}</button>
                    </fieldset>

                    <input type="hidden" name="id" value="{{ product.id }}" />
                </form>
            </div>
            <div class="tab-pane " id="tab-custom_parameters">
                <form method="post" action="{{ 'api/admin/product/update_config'|link }}" class="save api-form" data-api-reload="1">
                    <fieldset>
                        {% for k,v in product.config %}
                        <div class="rowElem">
                            <label>{{k}}:</label>
                            <div class="formRight">
                                <input type="text" class="form-control" name="config[{{k}}]" value="{{v}}">
                            </div>
                            <div class="fix"></div>
                        </div>
                        {% endfor %}
                    </fieldset>

                    <fieldset>
                        <legend>Add custom parameter</legend>
                        <div class="rowElem">
                            <label>Parameter name:</label>
                            <div class="formRight">
                                <input type="text" class="form-control" name="new_config_name">
                            </div>
                            <div class="fix"></div>
                        </div>

                        <div class="rowElem">
                            <label>Parameter value:</label>
                            <div class="formRight noborder">
                                <textarea rows="7" cols="" class="form-control" name="new_config_value"></textarea>
                            </div>
                            <div class="fix"></div>
                        </div>
                        <button type="submit" value="" class="btn btn-primary submitForm"><i class="fe fe-save"></i> {% trans 'Update configuration fields' %}</button>
                        <div class="fix"></div>
                        <input type="hidden" name="id" value="{{ product.id }}"/>
                    </fieldset>
                </form>
            </div>
        </div>
    </form>
</div>














