
<div class="main-sidemenu">
    <div class="slide-left disabled" id="slide-left"><svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191" width="24" height="24" viewBox="0 0 24 24"><path d="M13.293 6.293 7.586 12l5.707 5.707 1.414-1.414L10.414 12l4.293-4.293z"/></svg></div>
    <ul class="side-menu">
        <li class="slide">
            <a class="side-menu__item" data-bs-toggle="slide" href="{{ '/'|alink }}">
                <i  class="mr5 txt-15 tx-gray-600 fe fe-home" width="24" height="24"></i>
                <span class="side-menu__label ml">{{ 'Dashboard'|trans }}</span>
            </a>
        </li>
        {% set navigation = admin.extension_get_navigation({"url":guest.system_current_url}) %}
        {% for location,group in navigation %}
            {% if group.subpages %}
                <li class="side-item side-item-category" data-nav-index="{{ group.index }}" data-nav-location="{{location}}">{{ group.label|trans }}</li>
                {% for subpage in group.subpages %}
                    <li class="slide">
                        <a class="side-menu__item" data-bs-toggle="slide" href="{{ subpage.uri}}">
                            <i  class="mr5 txt-15 tx-gray-600 {{ subpage.class }}" width="24" height="24"></i>
                            <span class="side-menu__label ml">{{ subpage.label|trans }}</span>
                        </a>
                    </li>
                {% endfor %}
            {% endif %}
        {% endfor %}

    </ul>
    <div class="slide-right" id="slide-right"><svg xmlns="http://www.w3.org/2000/svg" fill="#7b8191" width="24" height="24" viewBox="0 0 24 24"><path d="M10.707 17.707 16.414 12l-5.707-5.707-1.414 1.414L13.586 12l-4.293 4.293z"/></svg></div>
</div>
