{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% block meta_title %}{% trans 'Themes' %}{% endblock %}
{% set active_menu = 'system' %}


{% block breadcrumbs %}

    <li class="breadcrumb-item tx-15"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item tx-15"><a  href="{{  'system'|alink }}">{% trans 'Settings' %}</a></li>
    <li class="breadcrumb-item active">{% trans 'Themes' %}</li>

{% endblock %}


{% block content %}
<div class="card">
    <div class="card-body">
        <h5>{% trans 'Client area themes' %}</h5>

        <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <td>{% trans 'Name' %}</td>
            <td>{% trans 'Actions' %}</td>
        </tr>
        </thead>

        <tbody>
        {% set themes = admin.theme_get_list({"per_page":1000000}) %}
        {% for i, theme in themes.list %}

        <tr>
            <td>{% if guest.extension_theme(true).code == theme.code %}<strong>{{ theme.code }}</strong>{% else %}{{ theme.code }}{% endif %}</td>
            <td class="actions">
                <a class="btn btn-sm bg-warning-transparent text-warning" href="{{ 'theme'|alink }}/{{theme.code}}"><i class="fe fe-settings"></i> <span>{% trans 'Settings' %}</span></a>
                {% if guest.extension_theme(true).code != theme.code %}
                <a class="btn btn-sm bg-info-transparent text-info mr10 api-link" data-api-redirect="{{ 'extension/settings/theme'|alink }}" href="{{ 'api/admin/theme/select'|link({'code' : theme.code}) }}"><i class="fe fe-star"></i> <span>{% trans 'Set as default' %}</span></a>
                {% endif %}
            </td>
        </tr>

        </tbody>
            {% else %}
            <tbody>
            <tr>
                <td colspan="2">
                    {% trans 'The list is empty' %}
                </td>
            </tr>
            </tbody>
        {% endfor %}
    </table>

    </div>
</div>

<div class="card">
    <div class="card-body">
        <h5>{% trans 'Admin area themes' %}</h5>

        <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <td>{% trans 'Name' %}</td>
            <td>{% trans 'Actions' %}</td>
        </tr>
        </thead>

        <tbody>
        {% set themes = admin.theme_get_admin_list({"per_page":100}) %}
        {% for i, theme in themes.list %}

        <tr>
            <td>{% if guest.extension_theme(false).code == theme.code %}<strong>{{ theme.code|replace({'admin_': ''}) }}</strong>{% else %}{{ theme.code|replace({'admin_': ''})  }}{% endif %}</td>
            <td class="actions">
                <a class="btn btn-sm bg-warning-transparent text-warning" href="{{ 'theme'|alink }}/{{theme.code}}"><i class="fe fe-settings"></i> <span>{% trans 'Settings' %}</span></a>
                {% if guest.extension_theme(false).code != theme.code %}
                <a class="btn btn-sm bg-info-transparent text-info mr10 api-link" data-api-redirect="{{ 'extension/settings/theme'|alink }}" href="{{ 'api/admin/theme/select'|link({'code' : theme.code}) }}">
                    <i class="fe fe-star"></i> <span>{% trans 'Set as default' %}</span>
                </a>
                {% endif %}
            </td>
        </tr>
        </tbody>

        {% else %}
        <tbody>
        <tr>
            <td colspan="5">
                {% trans 'The list is empty' %}
            </td>
        </tr>
        </tbody>
        {% endfor %}
    </table>
    </div>
</div>
{% endblock %}
