{% if order.status == 'active' %}
<div class="row">
<div class="col-lg-6">
    <div class="card">
        <div class="card-header tx-medium bd-0 bg-light">
            <h5>{% trans 'Stats hosting account' %}</h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-3 porcentdisk">

                    <div class="chart-circle mt-2 mt-md-0" data-value="0.85" data-thickness="8" data-color="">
                        <canvas width="100" height="100"></canvas>
                        <div class="chart-circle-value circle-style"><div id="porcentdisk" class="tx-18 font-weight-semibold">0%</div></div>
                    </div>
                    <div class="text-center font-weight-semibold">Disk Usage </div>
                    <div class="text-center titleStat">0 / 0</div>
                </div>
                <div class="col-md-3 porcentBand">

                    <div class="chart-circle mt-2 mt-md-0" data-value="0.85" data-thickness="8" data-color="">
                        <canvas width="100" height="100"></canvas>
                        <div class="chart-circle-value circle-style"><div id="porcentBand" class="tx-18 font-weight-semibold">0%</div></div>
                    </div>
                    <div class="text-center font-weight-semibold">Bandwith </div>
                    <div class="text-center titleStat">0 / 0</div>
                </div>
                <div class="col-md-3 databaseStat">

                    <div class="chart-circle mt-2 mt-md-0" data-value="0.85" data-thickness="8" data-color="">
                        <canvas width="100" height="100"></canvas>
                        <div class="chart-circle-value circle-style"><div id="databaseStat" class="tx-18 font-weight-semibold">0%</div></div>
                    </div>
                    <div class="text-center font-weight-semibold">MySql </div>
                    <div class="text-center titleStat">0 / 0</div>
                </div>
                <div class="col-md-3 domainsStat">

                    <div class="chart-circle mt-2 mt-md-0" data-value="0.85" data-thickness="8" data-color="">
                        <canvas width="100" height="100"></canvas>
                        <div class="chart-circle-value circle-style"><div id="domainsStat" class="tx-18 font-weight-semibold">0%</div></div>
                    </div>
                    <div class="text-center font-weight-semibold">Domains </div>
                    <div class="text-center titleStat">0 / 0</div>
                </div>
                <div class="col-md-12" style="height: 10px"></div>
                <div class="col-md-3  subdomainsStat">

                    <div class="chart-circle mt-2 mt-md-0" data-value="0.85" data-thickness="8" data-color="">
                        <canvas width="100" height="100"></canvas>
                        <div class="chart-circle-value circle-style"><div id="subdomainsStat" class="tx-18 font-weight-semibold">0%</div></div>
                    </div>
                    <div class="text-center font-weight-semibold">Subdomains </div>
                    <div class="text-center titleStat">0 / 0</div>
                </div>
                <div class="col-md-3 ftpStat">

                    <div class="chart-circle mt-2 mt-md-0" data-value="0.85" data-thickness="8" data-color="">
                        <canvas width="100" height="100"></canvas>
                        <div class="chart-circle-value circle-style"><div id="ftpStat" class="tx-18 font-weight-semibold">0%</div></div>
                    </div>
                    <div class="text-center font-weight-semibold">Ftp </div>
                    <div class="text-center titleStat">0 / 0</div>
                </div>
                <div class="col-md-3 emailStat">

                    <div class="chart-circle mt-2 mt-md-0" data-value="0.85" data-thickness="8" data-color="">
                        <canvas width="100" height="100"></canvas>
                        <div class="chart-circle-value circle-style"><div id="emailStat" class="tx-18 font-weight-semibold">0%</div></div>
                    </div>
                    <div class="text-center font-weight-semibold">Email </div>
                    <div class="text-center titleStat">0 / 0</div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-6">
<div class="card">
    <div class="card-header tx-medium bd-0 bg-light">
        <h5>{% trans 'Details' %}</h5>
    </div>
    <div class="card-body">
            {% set server = service.server %}
            {% set hp = service.hosting_plan %}
            <table class="table table-striped table-condensed">
                <tbody>
                <tr>
                    <td class="font-weight-bold">{% trans 'Domain' %}:</td>
                    <td>
                        <a target="_blank" href="http://{{ service.domain }}">{{ service.domain }}</a>
                    </td>
                </tr>

                <tr>
                    <td class="font-weight-bold">{% trans 'Server IP' %}:</td>
                    <td>{{ server.ip }}</td>
                </tr>

                <tr>
                    <td class="font-weight-bold">{% trans 'Server Hostname' %}:</td>
                    <td>{{ server.hostname }}</td>
                </tr>

                <tr>
                    <td class="font-weight-bold">{% trans 'Username' %}:</td>
                    <td>{{ service.username }}</td>
                </tr>
                <tr>
                    <td class="font-weight-bold">{% trans 'Hosting plan' %}:</td>
                    <td>{{ hp.name }}</td>
                </tr>
<!--
                <tr>
                    <td>{% trans 'Bandwidth' %}:</td>
                    <td>{{ hp.bandwidth }} MB / {% trans 'per month' %}</td>
                </tr>
                <tr>
                    <td>{% trans 'Disk quota' %}:</td>
                    <td>{{ hp.quota }} MB</td>
                </tr>
-->
                </tbody>
            </table><div class="col-md-12" style="height: 5px"></div>
            <div class="control-group text-center">
                <div class="controls">
                    {% if service.domain_order_id %}
                    <a class="btn btn-sm bg-primary-transparent text-primary" href="{{ '/order/service/manage'|link }}/{{service.domain_order_id}}">{% trans 'Manage domain' %}</a>
                    {% endif %}
                    <a class="btn btn-sm bg-info-transparent text-info" href="{{ server.cpanel_url }}" target="_blank"><i class="fe fe-external-link"></i> {% trans 'Jump to User Panel' %}</a>
                    {% if service.reseller %}
                    <a class="btn  btn-sm bg-warning-transparent text-warning " href="{{ server.reseller_cpanel_url }}" target="_blank">{% trans 'Reseller control panel' %}</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-lg-4">
    <div class="card">
        <div class="card-header tx-medium text-white bd-0 bg-primary">
            <h5>{% trans 'Change your password' %}</h5>
        </div>
        <form action="" method="post" id="change-password" class="form-horizontal">
            <div class="card-body" style="min-height: 180px">

                <div class="control-group">
                    <label class="control-label font-weight-bold" >{% trans 'Password' %}: </label>
                    <div class="controls">
                        <input type="password" class="form-control" name="password" value="{{ request.password }}" required="required">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label font-weight-bold" >{% trans 'Password Confirm' %}: </label>
                    <div class="controls">
                        <input type="password" class="form-control" name="password_confirm" value="{{ request.password_confirm }}" required="required">
                    </div>
                </div>

                <input type="hidden" name="order_id" value="{{ order.id }}">
            </div>
            <div class="card-footer bd-t tx-center">
                <button class="btn btn-sm bg-success-transparent text-success" type="submit" value="{% trans 'Change password' %}"><i class="fe fe-save"></i> {% trans 'Change password' %}</button>
            </div>
        </form>
    </div>
</div>
    <div class="col-lg-4">
         <div class="card">
             <div class="card-header tx-medium bd-0  text-white bg-primary">
                 <h5>{% trans 'Change domain' %}</h5>
             </div>
             <form action="" method="post" id="change-domain" class="form-horizontal">
                <div class="card-body" style="min-height: 180px">
                    <div class="control-group">
                        <label class="control-label font-weight-bold" >{% trans 'New domain' %}: </label>
                        <div class="row">
                            <input type="text"  class="form-control col-md-8" name="sld" value="{{ request.domain|default(service.sld) }}" required="required" class="span2">
                            <input type="text"  class="form-control col-md-4" name="tld" value="{{ request.domain|default(service.tld) }}" required="required" class="span1">
                        </div>
                    </div>
                    <input type="hidden" name="order_id" value="{{ order.id }}">

                </div>
                 <div class="card-footer bd-t tx-center">
                     <button class=" btn-sm btn bg-success-transparent text-success" type="submit" value="{% trans 'Change domain' %}"><i class="fe fe-save"></i> {% trans 'Change domain' %}</button>
                 </div>
             </form>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="card">
            <div class="card-header tx-medium bd-0 text-white  bg-primary">
                <h5>{% trans 'Create Email Account' %}</h5>
            </div>
            <form action="" method="post" id="create-email" class="form-horizontal">
                <div class="card-body" style="min-height: 180px">
                    <div class="control-group">
                        <label class="control-label font-weight-bold" >{% trans 'Email' %}: </label>
                        <div class="controls">
                            <input type="text" class="form-control" name="email" value="" required="required">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label font-weight-bold" >{% trans 'Password' %}: </label>
                        <div class="controls">
                            <input type="password" class="form-control" name="password" value="{{ request.password }}" required="required">
                        </div>
                    </div>
                    <input type="hidden" name="order_id" value="{{ order.id }}">
                    <input type="hidden" name="username" value="{{ request.username}}">
                </div>
                <div class="card-footer bd-t tx-center">
                    <button class="btn btn-sm bg-success-transparent text-success" type="submit" value="{% trans 'Create Email' %}"><i class="fe fe-save"></i> {% trans 'Create Email' %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="">
    <div class="">
        <div class="card-header-cab tx-medium bd-0 bg-light">
            <h5>{% trans 'User Panel Shorcuts' %}</h5>
        </div>
         <div class="row" id="idShort"></div>
    </div>
</div>
<style>
    .card-header-cab{
        border-radius: 5px ;
        background-color: #f9f9fb !important;
        box-shadow: 1px 1px 7px rgba(172, 170, 170, 0.47);
        border-color: #ededf5;
        border-bottom: 0px;
        padding: 0.75rem 1.25rem;
        margin-bottom: 8px;
    }
    .titleStat{
        font-size: 11px;
    }
    .form-control {
        border: 1px solid #bbbbbc;
    }
</style>
{% block js %}
<script type="text/javascript">
$(function() {
    $('.domain-tabs a').bind('click',function(e){
        e.preventDefault();
        $(this).tab('show');
    });

    $('#change-domain').bind('submit',function(event){
        bb.post(
            'client/servicehosting/change_domain',
            $(this).serialize(),
            function(result) {
                bb.msg('Domain name was changed');
            }
        );
        return false;
    });

    $('#create-email').bind('submit',function(event){
        bb.post(
            'client/servicehosting/create_email',
            $(this).serialize(),
            function(result) {
                bb.msg('Email Acount Created');
            }
        );
        return false;
    });

    $('#change-password').bind('submit',function(event){
        bb.post(
            'client/servicehosting/change_password',
            $(this).serialize(),
            function(result) {
                bb.msg('Account Password was changed');
            }
        );
        return false;
    });
    $(document).ready(function(){
        bb.post(
            'client/servicehosting/getQuota',
            'order_id={{ order.id }}',
            function(result) {
                let shortcuts=result.shortcut;
              /**/
              let resultDos=result.stat.account_info;
              let porcent=(resultDos.space_usage*100)/resultDos.space_disk;
                $('.porcentdisk .titleStat').html( (resultDos.space_usage).toFixed(2) +" / "+resultDos.space_disk);
              $('.porcentdisk .chart-circle').data( "value", (porcent/100).toFixed(2));
              $('#porcentdisk').html( porcent.toFixed(1)+"%");
                 let $this = $('.porcentdisk .chart-circle');
                $this.circleProgress({
                    fill: {
                        color:  "#38cab3",
                    },
                    size: $this.height(),
                    startAngle: -Math.PI / 4 * 2,
                    emptyFill: 'transparent',
                    lineCap: 'round'
                });

                porcent=(resultDos.bandwidth_used*100)/resultDos.bandwidth;
                $('.porcentBand .chart-circle').data( "value", (porcent/100).toFixed(2));
                $('#porcentBand').html( porcent+"%");
                $('.porcentBand .titleStat').html( resultDos.bandwidth_used +" / "+resultDos.bandwidth);
                $this = $('.porcentBand .chart-circle');
                $this.circleProgress({
                    fill: {
                        color:  "#38cab3",
                    },
                    size: $this.height(),
                    startAngle: -Math.PI / 4 * 2,
                    emptyFill: 'transparent',
                    lineCap: 'round'
                });

                porcent=(resultDos.db_used*100)/resultDos.db_max;
                $('.databaseStat .chart-circle').data( "value", (porcent/100).toFixed(2));
                $('#databaseStat').html( porcent.toFixed(0)+"%");
                $('.databaseStat .titleStat').html( resultDos.db_used +" / "+resultDos.db_max);
                $this = $('.databaseStat .chart-circle');
                $this.circleProgress({
                    fill: {
                        color:  "#38cab3",
                    },
                    size: $this.height(),
                    startAngle: -Math.PI / 4 * 2,
                    emptyFill: 'transparent',
                    lineCap: 'round'
                });
                /****** DOMAIN ****/
                porcent=(resultDos.db_used*100)/resultDos.db_max;
                $('.domainsStat .chart-circle').data( "value", (porcent/100).toFixed(2));
                $('#domainsStat').html( porcent.toFixed(0)+"%");
                $('.domainsStat .titleStat').html( resultDos.db_used +" / "+resultDos.db_max);
                $this = $('.domainsStat .chart-circle');
                $this.circleProgress({
                    fill: {
                        color:  "#38cab3",
                    },
                    size: $this.height(),
                    startAngle: -Math.PI / 4 * 2,
                    emptyFill: 'transparent',
                    lineCap: 'round'
                });
                /****** SUBDOMAIN ****/
                porcent=(resultDos.db_used*100)/resultDos.db_max;
                $('.subdomainsStat .chart-circle').data( "value", (porcent/100).toFixed(2));
                $('#subdomainsStat').html( porcent.toFixed(0)+"%");
                $('.subdomainsStat .titleStat').html( resultDos.db_used +" / "+resultDos.db_max);
                $this = $('.subdomainsStat .chart-circle');
                $this.circleProgress({
                    fill: {
                        color:  "#38cab3",
                    },
                    size: $this.height(),
                    startAngle: -Math.PI / 4 * 2,
                    emptyFill: 'transparent',
                    lineCap: 'round'
                });
                /****** FTP ****/
                porcent=(resultDos.db_used*100)/resultDos.db_max;
                $('.ftpStat .chart-circle').data( "value", (porcent/100).toFixed(2));
                $('#ftpStat').html( porcent.toFixed(0)+"%");
                $('.ftpStat .titleStat').html( resultDos.db_used +" / "+resultDos.db_max);
                $this = $('.ftpStat .chart-circle');
                $this.circleProgress({
                    fill: {
                        color:  "#38cab3",
                    },
                    size: $this.height(),
                    startAngle: -Math.PI / 4 * 2,
                    emptyFill: 'transparent',
                    lineCap: 'round'
                });

                /****** EMAIL ****/
                porcent=(resultDos.db_used*100)/resultDos.db_max;
                $('.emailStat .chart-circle').data( "value", (porcent/100).toFixed(2));
                $('#emailStat').html( porcent.toFixed(0)+"%");
                $('.emailStat .titleStat').html( resultDos.db_used +" / "+resultDos.db_max);
                $this = $('.emailStat .chart-circle');
                $this.circleProgress({
                    fill: {
                        color:  "#38cab3",
                    },
                    size: $this.height(),
                    startAngle: -Math.PI / 4 * 2,
                    emptyFill: 'transparent',
                    lineCap: 'round'
                });

                let html='';
                shortcuts.forEach(function(installation){
                    html+='<div class="col-xl-3 col-lg-3 col-sm-6 col-md-3">'+
                        '<div class="card text-center">'+
                        '<div class="card-body ">'+
                        '<div class="feature widget-2 text-center mt-0 mb-3">'+
                        '<a href="'+installation.url+'" target="_blank"><i class="'+installation.icon+' project bg-primary-transparent mx-auto text-primary"></i></a>'+
                '</div>'+
                    '<h6 class="mb-1 text-muted"><a href="'+installation.url+'" target="_blank">'+installation.name+'</a></h6>'+
                '</div>'+
                '</div>'+
                '</div>';

                });
                $("#idShort").html(html);
            }
        );

    });
});
</script>
{% endblock %}
{% endif %}
