{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% block meta_title %}{% trans 'Reposts' %}{% endblock %}

{% set active_menu = 'reports' %}


{% block breadcrumbs %}

<li class="breadcrumb-item tx-15"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
<li class="breadcrumb-item tx-15"><a  href="{{  'reports'|alink }}">{% trans 'Reports' %}</a></li>
<li class="breadcrumb-item active">{% trans 'Income Forecast' %}</li>

{% endblock %}

{% block content %}

<div class="col-xl-12">
    <!-- div -->
    <div class="card mg-b-20" id="tabs-style2">
        <div class="card-body">
            <div class="main-content-label mg-b-5">
                Income Forecast
            </div>

            <div class="text-wrap row">
                <div class="col-md-12">
                    <canvas id="myChart" class="col-lg-12" style="height:300px"></canvas>
                </div>
            </div>
            <div class="text-wrap row">
                <div class="col-md-12">
                    <table class="table table-hover" id="tableIncome">
                        <thead>
                            <tr>
                                <th>Month</th>
                                <th>Weekly</th>
                                <th>Monthly</th>
                                <th>3 Months</th>
                                <th>6 Months</th>
                                <th>1 Year</th>
                                <th>2 Years</th>
                                <th>3 Years</th>
                                <th>Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td colspan="9" class="text-center">Generating report, please wait...!</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>

<script>

    $(document).ready(function() {
        $.ajax({
            type: "POST",
            url: "{{ 'api/admin/reports/getIncomeReport'|link }}",
            dataType: 'json',
            error: function(jqXHR, textStatus, e) {
                alert(e);
            },
            success: function(data) {
                var obj =JSON.parse(data.result)
                if(obj.status=='Error') {
                    alert(obj.msj);
                } else if(obj.status=='OK') {
                    $("#tableIncome tbody").html(obj.table);

                    var xValues = ['June 2022','July 2022','August 2022','September 2022','October 2022','November 2022','December 2022','January 2023','February 2023','March 2023','April 2023','May 2023'];

                    new Chart("myChart", {
                        type: "line",
                        data: {
                            labels: obj.month,
                            datasets: [{
                                data: obj.acum,
                                borderColor: "red",
                                fill: true
                            }]
                        },
                        options: {
                            legend: {display: false}
                        }
                    });
                }
            }
        });
    });


</script>
{% endblock %}