{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}Client settings{% endblock %}
{% set active_menu = 'system' %}

{% block breadcrumbs %}

    <li class="breadcrumb-item tx-15"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
    <li class="breadcrumb-item tx-15"><a href="{{ 'system'|alink }}">{% trans 'Settings' %}</a></li>
    <li class="breadcrumb-item active">{% trans 'Client settings' %}</li>

{% endblock %}

{% block content %}

{% set params = admin.extension_config_get({"ext":"mod_client"}) %}
<form method="post" action="{{ 'api/admin/extension/config_save'|link }}" class="api-form" data-api-msg="{% trans 'Configuration updated' %}">

    <div class="card">
        <div class="card-body mt-0">
            <div class="panel panel-primary tabs-style-2">
                <div class=" tab-menu-heading">
                    <div class="tabs-menu1">

                        <ul class="nav panel-tabs main-nav-line">
                            <li><a class="nav-link active" data-bs-toggle="tab" href="#tab-index">{% trans 'General' %}</a></li>
                            <li><a  class="nav-link" data-bs-toggle="tab" href="#tab-custom-fields">{% trans 'Custom Fields' %}</a></li>
                        </ul>
                    </div>
                </div>
                <div class="panel-body tabs-menu-body main-content-body-right border">
                    <div class="tab-content">
                        <div class="tab-pane active" id="tab-index">


                <div class="rowElem noborder">
                    <label>{% trans 'Allow new signups' %}</label>
                    <div class="formRight">
                        <div class="row pt-3">
                            <div class="col-md-3">
                                <label class="rdiobox">
                                    <input type="radio" name="allow_signup" value="1"{% if params.allow_signup %} checked="checked"{% endif %}/><span>{% trans 'Yes' %}</span>
                                </label>
                            </div>
                            <div class="col-md-3">
                                <label class="rdiobox">
                                    <input type="radio" name="allow_signup" value="0"{% if not params.allow_signup %} checked="checked"{% endif %} /><span>{% trans 'No' %}</span>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="fix"></div>
                </div>
                <div class="rowElem">
                    <label>{% trans 'Require email confirmation' %}</label>
                    <div class="formRight">
                        <div class="row pt-3">
                            <div class="col-md-3">
                                <label class="rdiobox">
                                    <input type="radio" name="require_email_confirmation" value="1"{% if params.require_email_confirmation %} checked="checked"{% endif %}/><span>{% trans 'Yes' %}</span>
                                </label>
                            </div>
                            <div class="col-md-3">
                                <label class="rdiobox">
                                    <input type="radio" name="require_email_confirmation" value="0"{% if not params.require_email_confirmation %} checked="checked"{% endif %} /><span>{% trans 'No' %}</span>
                                </label>
                            </div>
                        </div>
                       <span class="formNote">{% trans 'After enabling this feature, all existing users will have to confirm their emails if it was not done before' %}.</span>
                    </div>
                    <div class="fix"></div>
                </div>

                <div class="rowElem">
                    <label>{% trans 'Allow email change' %}</label>
                    <div class="formRight">
                        <div class="row pt-3">
                            <div class="col-md-3">
                                <label class="rdiobox">
                                    <input type="radio" name="allow_change_email" value="1"{% if params.allow_change_email %} checked="checked"{% endif %}/><span>{% trans 'Yes' %}</span>
                                </label>
                            </div>
                            <div class="col-md-3">
                                <label class="rdiobox">
                                    <input type="radio" name="allow_change_email" value="0"{% if not params.allow_change_email %} checked="checked"{% endif %} /><span>{% trans 'No' %}</span>
                                </label>
                            </div>
                        </div>
                      </div>
                    <div class="fix"></div>
                </div>

                <div class="rowElem">
                    <label>{% trans 'Required fields' %}</label>
                    <div class="formRight">
                        <select multiple="multiple" style="height: 250px" class="multiple form-control form-select" title="{% trans 'Select required fields' %}" name="required[]">
                            <optgroup label="General">
                            <option value="last_name" {% if 'last_name' in params.required %}selected{% endif %}>{% trans 'Last Name' %}</option>
                            <option value="company" {% if 'company' in params.required %}selected{% endif %}>{% trans 'Company' %}</option>
                            <option value="gender" {% if 'gender' in params.required %}selected{% endif %}>{% trans 'Gender' %}</option>
                            <option value="birthday" {% if 'birthday' in params.required %}selected{% endif %}>{% trans 'Birthday' %}</option>
                            </optgroup>

                            <optgroup label="Address">
                            <option value="country" {% if 'country' in params.required %}selected{% endif %}>{% trans 'Country' %}</option>
                            <option value="city" {% if 'city' in params.required %}selected{% endif %}>{% trans 'City' %}</option>
                            <option value="state" {% if 'state' in params.required %}selected{% endif %}>{% trans 'State' %}</option>
                            <option value="address_1" {% if 'address_1' in params.required %}selected{% endif %}>{% trans 'Address Line 1' %}</option>
                            <option value="address_2" {% if 'address_2' in params.required %}selected{% endif %}>{% trans 'Address Line 2' %}</option>
                            <option value="postcode" {% if 'last_name' in params.required %}selected{% endif %}>{% trans 'Post code' %}</option>
                            <option value="phone" {% if 'phone' in params.required %}selected{% endif %}>{% trans 'Phone' %}</option>
                            </optgroup>

                        </select>

                    </div>
                    <div class="fix"></div>
                </div>
                 <button type="submit" value="" class="btn btn-primary  submitForm"><i class="fe fe-save"></i>{% trans 'Update' %}</button>
        </div>
                        <div id="tab-custom-fields" class="tab-pane ">

                            {% for i in 1..10 %}
                            {% set field_name = 'custom_' ~ i %}
                            {% set custom_field = attribute(params.custom_fields, field_name) %}
                            <div class="col-md-12" style="border-bottom: 1px solid #fbfbfb">
                                <div class="row">
                                    <label class="col-md-3">{% if custom_field.title is not empty %} {{custom_field.title}} ({% trans 'Custom_' %}{{ i }}) {% else %}{% trans 'Custom_' %}{{ i }}{% endif %}</label>

                                    <label class="col-md-3 ckbox">
                                        <input type="checkbox" name="custom_fields[{{ field_name }}][active]" value="1"{% if custom_field.active %} checked="checked"{% endif %}/><span>{% trans 'Active' %}</span>
                                    </label>
                                    <label class="col-md-3 ckbox">
                                        <input type="checkbox" name="custom_fields[{{ field_name }}][required]" value="1"{% if custom_field.required %} checked="checked"{% endif %}/><span>{% trans 'Required' %}</span>
                                    </label>
                                    <div class="col-md-3">
                                        <input type="text" class="form-control" placeholder="Field title" name="custom_fields[{{ field_name }}][title]" value="{{custom_field.title}}" />
                                    </div>
                                 </div>
                                <div class="fix"></div>
                            </div>
                            <hr/>
                            {% endfor %}
                            <button type="submit" value="" class="btn btn-primary  submitForm"><i class="fe fe-save"></i> {% trans 'Update profile' %}</button>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <input type="hidden" name="ext" value="mod_client" />
    </form>
{% endblock %}
